<div style="border-radius: 10px; padding: 32px 0px; border: 1px solid rgba(128,128,128,0.2);">
  <div style="display: flex; align-items: center; gap: 16px; padding: 0 32px;">
    <div>
      <h1 style="margin:0; font-size:1.6em;">B1 · Clasificador Hídrico y Natural</h1>
      <p style="margin:4px 0 0; color: gray;">Clasificador multietiqueta de publicaciones hídricas y naturales en boletines oficiales españoles</p>
    </div>
  </div>
</div>

# B1 · Clasificador Hídrico y Natural

Este notebook implementa el clasificador del **bloque B1** (hídrico y natural) para el proyecto de monitorización de boletines oficiales españoles.

**Dominio**: publicaciones relacionadas con concesiones de aguas, vías pecuarias, montes de utilidad pública, espacios naturales protegidos, gestión de residuos, vertidos y planes hidrológicos.

**Arquitectura**: B1 comparte con B0 el pre-procesamiento N0/N1 (`agent.py`) pero tiene su propio schema (`schema_B1.py`) y prompts (`prompts_B1.py`).

| Capa | Qué etiqueta | Cómo |
|------|-------------|------|
| N0 | Ámbito geográfico | lookup por boletín, sin LLM |
| N1 | Tipo de acto | reglas de primer token, sin LLM |
| N2 | Categoría hídrica/natural | LLM (11 etiquetas) |
| N3 | Subcategoría uso/cuenca | LLM (15 etiquetas) |

---

##  0. Setup

Cargamos variables de entorno e importamos librerías. El modelo vive en LM Studio.

In [1]:
# Librerías estándar
import os
import html
import re
import json
import asyncio
from pathlib import Path

# Datos
import pandas as pd
import numpy as np

# Métricas multilabel
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    hamming_loss,
    jaccard_score,
)

# Carga de variables de entorno desde .env (busca hacia arriba desde el directorio actual)
from dotenv import find_dotenv, load_dotenv

# Pydantic AI - framework que fuerza al LLM a devolver JSON validado por Pydantic
from pydantic_ai import Agent

SEED = 29092025

load_dotenv(find_dotenv())

True

In [2]:
from pydantic_ai.models.openai import OpenAIModel
from pydantic_ai.providers.openai import OpenAIProvider

# Cambiar LM_STUDIO_MODEL según el modelo cargado en LM Studio
LM_STUDIO_MODEL = "qwen/qwen3.5-9b"

model = OpenAIModel(
    LM_STUDIO_MODEL,
    provider=OpenAIProvider(
        base_url="http://localhost:1234/v1",
        api_key="lm-studio",
    ),
)

/tmp/ipykernel_1857476/2598252738.py:7: DeprecationWarning: `OpenAIModel` was renamed to `OpenAIChatModel` to clearly distinguish it from `OpenAIResponsesModel` which uses OpenAI's newer Responses API. Use that unless you're using an OpenAI Chat Completions-compatible API, or require a feature that the Responses API doesn't support yet like audio.
  model = OpenAIModel(

In [3]:
import httpx

try:
    r = httpx.get("http://localhost:1234/v1/models", timeout=3)
    modelos = [m["id"] for m in r.json()["data"]]
    assert LM_STUDIO_MODEL in modelos, f"{LM_STUDIO_MODEL} no está cargado en LM Studio"
    print(f"OK: {LM_STUDIO_MODEL} listo  |  otros: {[m for m in modelos if m != LM_STUDIO_MODEL]}")
except httpx.ConnectError:
    raise RuntimeError("LM Studio no responde - arrancar el servidor antes de continuar")

OK: qwen/qwen3.5-9b listo  |  otros: ['google/gemma-4-e4b', 'google/gemma-3n-e4b', 'gemma-4-e2b-it', 'google/gemma-3-4b', 'text-embedding-nomic-embed-text-v1.5']

---

##  1. Schema de output

El schema define el **contrato entre el LLM y el sistema**: qué campos devuelve el modelo,
de qué tipo son y qué invariantes deben cumplirse.

B1 reutiliza `ActType` de B0 (mismo enum de formas jurídicas) y define sus propios enums
`CategoryType` (N2) y `SubcategoryType` (N3).

In [4]:
# Importar los tipos del schema B1: enums de etiquetas y modelo de output
from clasificador.schema_B1 import ActType, CategoryType, SubcategoryType, ClassifierOutput

In [5]:
# Verificación de invariantes del schema B1
ejemplo_valido = ClassifierOutput(
    is_relevant=True,
    act_type=ActType.RESOLUCION,
    categories=[CategoryType.AGU_RIE],
    subcategories=[SubcategoryType.USO_AGRICOLA, SubcategoryType.CUENCA_DUERO],
    confidence=0.95,
    reasoning="'concesión de aguas para riego' → AGU_RIE. 'Confederación Hidrográfica del Duero' → cuenca_duero.",
)
print("Ejemplo válido:")
print(ejemplo_valido.model_dump_json(indent=2))

print("\nViolación de invariante:")
try:
    ClassifierOutput(
        is_relevant=False, act_type=ActType.RESOLUCION,
        categories=[CategoryType.AGU_GEN], subcategories=[],
        confidence=0.5, reasoning="Prueba.",
    )
except Exception as e:
    print(f"  ValidationError -> {e.errors()[0]['msg']}")

Ejemplo válido:
{
  "is_relevant": true,
  "act_type": "resolución",
  "categories": [
    "AGU_RIE"
  ],
  "subcategories": [
    "uso_agricola",
    "cuenca_duero"
  ],
  "confidence": 0.95,
  "reasoning": "'concesión de aguas para riego' → AGU_RIE. 'Confederación Hidrográfica del Duero' → cuenca_duero."
}

Violación de invariante:
  ValidationError -> Value error, is_relevant=False con categories != []

---

##  2. Pre-procesamiento

El pre-procesamiento N0/N1 es **compartido entre todos los bloques** y vive en `agent.py`.
No se reimplementa aquí: solo se importa.

- **N0**: ámbito geográfico por boletín (`get_ambito`)
- **N1**: tipo de acto por reglas de primer token (`inferir_act_type`)

In [6]:
# Funciones N0/N1 compartidas con B0 - viven en agent.py
from clasificador.agent import get_ambito, inferir_act_type

# Cargar el corpus completo
PATH_PARQUET = "../data/raw/silver_official_gazettes_2025_Q1.parquet"
df = pd.read_parquet(PATH_PARQUET)
df["description"] = df["description"].apply(lambda x: html.unescape(str(x)) if pd.notna(x) else x)
print(f"Corpus total: {len(df):,} registros | Columnas: {list(df.columns)}")

Corpus total: 65,201 registros | Columnas: ['id', 'pdf_link', 'expediente', 'promotor', 'proyecto', 'description', 'tipo', 'clean_id', 'bulletin', 'provincias', 'municipios', 'raw_scraped_timestamp', 'raw_scraped_year_month', 'scraped_timestamp', 'scraped_year_month', 'publication_timestamp', 'publication_type', 'contains_aau', 'proxy_pdf_link', 'ambito', 'rango']

In [7]:
# Aplicar clasificador N1 (reglas de primer token) al corpus completo
df["act_type_n1"] = df.apply(
    lambda r: inferir_act_type(str(r["description"]), str(r["bulletin"])).value, axis=1
)

# Filtrar al dominio B1 usando las keywords de muestreo para estimar el tamaño del universo
keywords_dominio = [
    "confederación hidrográfica", "comisaría de aguas", "aprovechamiento de aguas",
    "regadío", "comunidad de regantes", "riego", "sondeo para captación",
    "captación de aguas subterráneas", "abastecimiento de agua", "abastecimiento municipal",
    "aprovechamiento hidroeléctrico", "central hidroeléctrica",
    "vía pecuaria", "cañada real", "cordel", "vereda",
    "monte de utilidad pública", "dominio público forestal",
    "parque natural", "parque nacional", "red natura", "zepa", "zec",
    "gestión de residuos", "tratamiento de residuos",
    "autorización de vertido", "vertido de aguas",
    "plan hidrológico", "demarcación hidrográfica",
]
mask_b1 = df["description"].str.lower().str.contains("|".join(keywords_dominio), na=False)
df_b1 = df[mask_b1].copy()
print(f"Universo B1 estimado: {len(df_b1):,} registros ({len(df_b1)/len(df)*100:.2f}% del corpus)")
print(f"\nDistribución N1 en universo B1:")
print(df_b1["act_type_n1"].value_counts().head(10).to_string())

Universo B1 estimado: 3,168 registros (4.86% del corpus)

Distribución N1 en universo B1:
act_type_n1
anuncio                2388
resolución              544
información_pública      87
aprobación               29
edicto                   26
orden                    20
acuerdo                  15
otros                    15
notificación             11
corrección_errores       10

---

##  3. Ground truth — Muestreo estratificado

El ground truth se construye en dos pasos:
1. **Muestreo**: seleccionar registros representativos por categoría N2 (esta sección)
2. **Anotación**: etiquetar manualmente el CSV resultante (tarea externa)

### Cuotas de muestreo

| Categoría | Cuota | Señal principal |
|-----------|-------|----------------|
| AGU_GEN | 25 | confederación hidrográfica, aprovechamiento de aguas |
| AGU_RIE | 25 | regadío, comunidad de regantes |
| AGU_SND | 15 | sondeo para captación |
| AGU_ABS | 15 | abastecimiento de agua |
| VIA_PEC | 20 | vía pecuaria, cañada real |
| RES | 15 | gestión de residuos |
| MON | 10 | monte de utilidad pública |
| VER | 10 | autorización de vertido |
| ESP_NAT | 5 | parque natural, Red Natura, ZEPA |
| AGU_IND | 5 | aprovechamiento hidroeléctrico |
| PHD | 5 | plan hidrológico (si hay pool suficiente) |
| **Negativos** | **20** | sin ninguna de las keywords anteriores |

In [8]:
# Pre-flight check: verificar pool disponible por label antes de samplear.
# Si alguna etiqueta tiene menos registros que la cuota, se reduce automaticamente.
import random
random.seed(SEED)

keywords_B1 = {
    "AGU_GEN": ["confederación hidrográfica", "comisaría de aguas", "aprovechamiento de aguas"],
    "AGU_RIE": ["regadío", "comunidad de regantes", "riego"],
    "AGU_SND": ["sondeo para captación", "captación de aguas subterráneas", "pozo de captación"],
    "AGU_ABS": ["abastecimiento de agua", "abastecimiento municipal", "agua potable"],
    "AGU_IND": ["aprovechamiento hidroeléctrico", "central hidroeléctrica", "refrigeración"],
    "VIA_PEC": ["vía pecuaria", "cañada real", "cordel", "vereda", "colada"],
    "MON":     ["monte de utilidad pública", "dominio público forestal", "ocupación de monte"],
    # ESP_NAT: keywords corregidas - "espacio natural protegido" y "reserva natural"
    # no devuelven resultados en el corpus Q1 2025
    "ESP_NAT": ["parque natural", "parque nacional", "red natura", "zepa", "zec", "zona de especial"],
    "RES":     ["gestión de residuos", "tratamiento de residuos", "planta de residuos"],
    "VER":     ["autorización de vertido", "vertido de aguas residuales", "dominio público hidráulico"],
    "PHD":     ["plan hidrológico", "demarcación hidrográfica"],
}

cuotas = {
    "AGU_GEN": 25, "AGU_RIE": 25, "AGU_SND": 15, "AGU_ABS": 15,
    "AGU_IND": 5,  "VIA_PEC": 20, "MON": 10,      "ESP_NAT": 5,
    "RES": 15,     "VER": 10,     "PHD": 5,
}
N_NEGATIVOS = 20

print(f"{'Label':<10} {'Pool':>8} {'Cuota':>7} {'Disponible':>11}")
print("-" * 42)
for label, kws in keywords_B1.items():
    mask = df["description"].str.lower().str.contains("|".join(kws), na=False)
    pool_size = mask.sum()
    cuota = cuotas.get(label, 0)
    disponible = min(cuota, pool_size)
    estado = "OK" if pool_size >= cuota else f"REDUCIDA a {disponible}"
    print(f"{label:<10} {pool_size:>8,} {cuota:>7} {estado:>11}")

Label          Pool   Cuota  Disponible
------------------------------------------
AGU_GEN       1,428      25          OK
AGU_RIE       1,147      25          OK
AGU_SND         170      15          OK
AGU_ABS         267      15          OK
AGU_IND          23       5          OK
VIA_PEC         307      20          OK
MON              90      10          OK
ESP_NAT          39       5          OK
RES             142      15          OK
VER             131      10          OK
PHD              30       5          OK

In [9]:
# Muestreo estratificado por categoria.
# min(cuota, len(pool)) evita errores cuando el pool es menor que la cuota.
sampled_ids = set()
frames = []

for label, kws in keywords_B1.items():
    mask = df["description"].str.lower().str.contains("|".join(kws), na=False)
    mask = mask & ~df.index.isin(sampled_ids)
    pool = df[mask]
    n = min(cuotas.get(label, 0), len(pool))
    if n == 0:
        print(f"  {label:<10} SKIP (pool vacio)")
        continue
    sample = pool.sample(n, random_state=SEED).copy()
    sample["grupo_muestreo"] = label
    sampled_ids.update(sample.index.tolist())
    frames.append(sample)
    print(f"  {label:<10} pool={len(pool):>5,}  sampled={n}")

# Negativos: registros sin ninguna keyword del dominio B1
all_kws = [kw for kws in keywords_B1.values() for kw in kws]
mask_neg = ~df["description"].str.lower().str.contains("|".join(all_kws), na=False)
mask_neg = mask_neg & ~df.index.isin(sampled_ids)
negativos = df[mask_neg].sample(N_NEGATIVOS, random_state=SEED).copy()
negativos["grupo_muestreo"] = "NEGATIVO"
frames.append(negativos)

df_muestreo = pd.concat(frames, ignore_index=True)
df_muestreo["id"] = range(len(df_muestreo))
print(f"\nTotal muestreado: {len(df_muestreo)} registros")

  AGU_GEN    pool=1,428  sampled=25
  AGU_RIE    pool=1,143  sampled=25
  AGU_SND    pool=  169  sampled=15
  AGU_ABS    pool=  266  sampled=15
  AGU_IND    pool=   23  sampled=5
  VIA_PEC    pool=  306  sampled=20
  MON        pool=   90  sampled=10
  ESP_NAT    pool=   39  sampled=5
  RES        pool=  142  sampled=15
  VER        pool=  130  sampled=10
  PHD        pool=   30  sampled=5

Total muestreado: 170 registros

In [10]:
# Validación del muestreo: 3 ejemplos por label para confirmar que pertenecen al dominio.
# Imprime el grupo, boletín y descripción truncada para revisión rápida.
print("Validación del muestreo - 3 ejemplos por grupo:\n")
for grupo in df_muestreo["grupo_muestreo"].unique():
    muestra = df_muestreo[df_muestreo["grupo_muestreo"] == grupo].head(3)
    print(f"--- {grupo} ---")
    for _, row in muestra.iterrows():
        desc = str(row["description"])[:130].replace("\n", " ")
        bul = str(row.get("bulletin", "?")).upper()
        print(f"  [{bul}] {desc}")
    print()

Validación del muestreo - 3 ejemplos por grupo:

--- AGU_GEN ---
  [BOE] Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública de resolución de otorgamiento de conce
  [BOE] Anuncio de formalización de contratos de: Presidencia de la Confederación Hidrográfica del Guadiana. Objeto: Suministro de materia
  [BOE] Anuncio de formalización de contratos de: Presidencia de la Confederación Hidrográfica del Guadalquivir. Objeto: Contrato de servi

--- AGU_RIE ---
  [BOE] Anuncio de la Comunidad de Regantes Pozo La Sierra de Torrent sobre convocatoria de Junta.
  [BOE] Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pública de procedimiento de exti
  [BOE] Anuncio de la Comunidad de Regantes Las Almacidas sobre convocatoria de Junta General Ordinaria.

--- AGU_SND ---
  [DOGV] RESOLUCIÓN de 17 de septiembre de 2024, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambiental, por la que se formul
  [BOIB] Resolución de la directora general de Armonización Urbanística y Evaluación Ambiental por la cual se formula el informe de impacto
  [DOGV] RESOLUCIÓN de 26 de septiembre de 2024, del director general de Urbanismo, Paisaje y Evaluación Ambiental, por la cual se formula

--- AGU_ABS ---
  [DOGC] Anuncio sobre aprobación definitiva de la modificación del anexo I de la Ordenanza núm. 16, reguladora de las prestaciones patrimo
  [BORM] Padrón correspondiente al listado cobratorio de abastecimiento de agua y alcantarillado correspondiente al cuarto trimestre de 202
  [DOCM] Resolución de 17/03/2025, de la Dirección General de Medio Natural y Biodiversidad, por la que se aprueba la ocupación de terrenos

--- AGU_IND ---
  [BOE] Anuncio del Área de Industria y Energía de la Subdelegación del Gobierno en Zaragoza por el que se somete a información pública la
  [DOG] ANUNCIO de 6 de marzo de 2025, de la Comisaría de Augas de Galicia, por el que se somete al trámite de información pública el expe
  [BOCA] Consejo Insular de Aguas de Lanzarote.- Anuncio de 25 de febrero de 2025, por el que se somete a información pública la solicitud

--- VIA_PEC ---
  [BOCM] Vías pecuarias – Resolución de 9 de enero de 2025, del Director General de Agricultura, Ganadería y Alimentación, por la que se an
  [BOCM] Vías pecuarias – Resolución de 11 de diciembre de 2024, del Director General de Agricultura, Ganadería y Alimentación, por la que
  [BOA] ANUNCIO del Instituto Aragonés de Gestión Ambiental, por el que se somete a información pública el expediente para la ocupación te

--- MON ---
  [BOA] ANUNCIO del Instituto Aragonés de Gestión Ambiental, por el que se somete a información pública la renovación de la concesión de u
  [BOCM] Montes de utilidad pública – Anuncio de 21 de febrero de 2025, de la Consejería de Medio Ambiente, Agricultura e Interior, por el
  [BOA] ANUNCIO del Instituto Aragonés de Gestión Ambiental, por el que se somete a información pública y concurrencia competitiva el expe

--- ESP_NAT ---
  [DOCM] Resolución de 11/03/2025, de la Delegación Provincial de Desarrollo Sostenible de Ciudad Real, por la que se formula informe de im
  [BOCYL] INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rústico y licencia urbanística, para la se
  [DOCM] Resolución de 17/03/2025, de la Delegación Provincial de Desarrollo Sostenible de Ciudad Real, por la que se formula informe de im

--- RES ---
  [DOGC] Anuncio sobre aprobación de la convocatoria del proceso selectivo con el objeto de crear una bolsa de trabajo del perfil profesion
  [DOGC] Anuncio sobre aprobación inicial del Proyecto técnico para la implantación del nuevo punto limpio para el tratamiento de residuos
  [BOPV] ANUNCIO del Director de Administración Ambiental, por el que se somete a información pública el proyecto técnico y el estudio de i

--- VER ---
  [BOPV] ANUNCIO de la Agencia Vasca del Agua, por el que se somete a información pública una solicitud de autorización de vertido en el té
  [BOE] Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública sobre autorización administrativa para
  [BOE] Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de autorización para la corta de

--- PHD ---
  [BOE] Anuncio de formalización de contratos de: Presidencia de la Confederación Hidrográfica del Miño-Sil. Objeto: Servicio para el sopo
  [BOCA] Consejo Insular de Aguas de El Hierro.- Anuncio de 15 de enero de 2025, por el que se inicia el periodo de consulta e información
  [DOG] RESOLUCIÓN de 13 de enero de 2025 por la que se hacen públicas las ayudas concedidas al amparo de la Resolución de 18 de marzo de

--- NEGATIVO ---
  [BOA] RESOLUCIÓN de 19 de diciembre de 2024, del Servicio Provincial de Zaragoza, relativo a la autorización administrativa previa y de
  [BOCA] Consejo Insular de Aguas de Tenerife.- Anuncio de 14 de enero de 2025, relativo a la solicitud de autorización administrativa para
  [BOE] U.R. SUBASTAS MURCIA

In [11]:
# Guardar el muestreo sin anotar - la anotación manual es el siguiente paso
PATH_MUESTREO = "../data/ground_truth/ground_truth_B1_muestreo.csv"
Path(PATH_MUESTREO).parent.mkdir(parents=True, exist_ok=True)

# Columnas de anotación preparadas vacías para rellenar manualmente
df_muestreo["is_relevant_gt"]   = ""
df_muestreo["categories_gt"]    = ""
df_muestreo["subcategories_gt"] = ""
df_muestreo["notas_anotador"]   = ""

df_muestreo[["id","bulletin","description","grupo_muestreo",
             "is_relevant_gt","categories_gt","subcategories_gt","notas_anotador"]].to_csv(
    PATH_MUESTREO, index=False
)
print(f"Guardado: {PATH_MUESTREO}  ({len(df_muestreo)} registros)")
print("Siguiente paso: anotar manualmente las columnas is_relevant_gt, categories_gt, subcategories_gt")

Guardado: ../data/ground_truth/ground_truth_B1_muestreo.csv  (170 registros)
Siguiente paso: anotar manualmente las columnas is_relevant_gt, categories_gt, subcategories_gt

### Dataset anotado

Una vez completada la anotación manual de `ground_truth_B1_muestreo.csv`, cargar con:

```python
df_anotado = pd.read_csv("../data/ground_truth/ground_truth_B1_anotado.csv")
```

La anotación debe cubrir las columnas `is_relevant_gt`, `categories_gt` (valores separados por coma, ej. `AGU_RIE,ESP_NAT`) y `subcategories_gt` (opcional).

---

##  4. Agente base

La lógica de clasificación vive en `src/clasificador/`. El notebook solo importa y orquesta.
`build_agent` acepta `output_type` y `prompt_registry` para soportar bloques distintos de B0.

In [12]:
# Importar la capa de agente compartida y los prompts/schema propios de B1
from clasificador.agent import build_agent, run_experiment, clasificar_async
from clasificador.prompts_B1 import SYSTEM_PROMPT_B1_V1, PROMPT_REGISTRY as PROMPT_REGISTRY_B1
from clasificador.schema_B1 import ClassifierOutput as ClassifierOutputB1
from tqdm.asyncio import tqdm_asyncio

In [13]:
# Construir el agente B1 con el prompt baseline (v1)
# Se pasan output_type y prompt_registry propios de B1 - agent.py permanece genérico
agent_b1_v1 = build_agent(
    model, "v1",
    output_type=ClassifierOutputB1,
    prompt_registry=PROMPT_REGISTRY_B1,
)

In [ ]:
# Validación cualitativa - 5 casos representativos del dominio B1
casos_b1 = [
    ("Resolución de la Confederación Hidrográfica del Duero por la que se otorga "
     "concesión de aguas superficiales para riego de 120 ha en Valladolid. "
     "Comunidad de Regantes del Canal de Macías Picavea.", "bocyl"),
    ("Anuncio de información pública sobre solicitud de autorización de vía pecuaria "
     "cañada real para construcción de línea eléctrica subterránea en Cáceres.", "doe"),
    ("Resolución de la Dirección General de Medio Natural por la que se aprueba "
     "el plan de gestión de la Zona de Especial Conservación (ZEC) ES4110108.", "bocyl"),
    ("Resolución de la Consejería de Hacienda por la que se convocan plazas de "
     "auxiliar administrativo en la Junta de Castilla y León.", "bocyl"),
    ("Anuncio de la Confederación Hidrográfica del Tajo sobre autorización de "
     "vertido de aguas residuales tratadas al río Jarama en Guadalajara.", "bocm"),
]

print("Validación cualitativa - 5 casos B1\n")
for i, (desc, bul) in enumerate(casos_b1, 1):
    msg = f"Boletín: {bul.upper()} (ámbito: {get_ambito(bul)})\n\nDescripción: {desc}"
    result = await agent_b1_v1.run(msg)
    r = result.output
    cats = [c.value for c in r.categories]
    subs = [s.value for s in r.subcategories]
    print(f"Caso {i} | relevant={r.is_relevant} | cats={cats} | subs={subs}")
    print(f"  Reasoning: {r.reasoning[:120]}")
    print()

Validación cualitativa - 5 casos B1

---

##  5. Experimento 1 - Baseline zero-shot

**Problema**: no existe un clasificador para el dominio hídrico/natural. Necesitamos una línea base que mida el rendimiento zero-shot antes de cualquier optimización.

**Objetivo**: establecer el Macro-F1 de referencia con el prompt mínimo operativo (V1) y detectar los patrones de error sistemáticos que guiarán la siguiente iteración del prompt.

**Enfoque**: Qwen 3.5 9B · `SYSTEM_PROMPT_B1_V1` · zero-shot · sin contexto N1 · 180 registros.

**Resultados**:

| Métrica | Valor |
|---------|-------|
| is_rel F1 | - |
| Micro F1 | - |
| Macro F1 | - |
| Hamming Loss | - |
| Jaccard | - |
| Subset Acc | - |

In [14]:

df_anotado = pd.read_csv("../data/ground_truth/ground_truth_B1_anotado.csv")
df_anotado_run = df_anotado[df_anotado["is_relevant_gt"] != ""]  # solo filas anotadas

df_exp_b1_1 = await run_experiment(
     agent_b1_v1, df_anotado_run,
     use_n1_context=False, concurrency=1,
     output_path="../results/b1_exp1_baseline_qwen9b.csv",
     desc="B1 Exp1 - Baseline",
 )

  Reanudando: 170/170 registros ya clasificados

---

##  6. Análisis de errores - Baseline

Evaluamos las predicciones del Exp 1 contra el ground truth para identificar patrones de error
que guíen la mejora del prompt en §7.

In [15]:
# Convierte cualquier representación de etiquetas a un set de strings.
# Misma función que B0 - compatible con CSV manual ("AGU_RIE,ESP_NAT")
# y con JSON de predicciones ('["AGU_RIE","ESP_NAT"]').
def parse_labels(value) -> set:
    if pd.isna(value) or str(value).strip() in ("", "nan"):
        return set()
    v = str(value).strip()
    if v.startswith("["):
        try:
            return set(json.loads(v))
        except Exception:
            pass
    return set(x.strip() for x in v.split(",") if x.strip())

In [16]:
def compute_metrics_B1(df_eval, label="", verbose=True):
    """
    Calcula métricas multilabel para el clasificador B1.
    Identica a compute_metrics de B0 pero con las etiquetas N2 de B1.
    Columnas esperadas: is_relevant_gt, categories_gt, is_relevant_pred, categories_pred.
    """
    # Etiquetas N2 de B1 - derivadas del enum para evitar hardcodear
    from clasificador.schema_B1 import CategoryType
    N2 = [e.value for e in CategoryType]

    y_true = df_eval["is_relevant_gt"].astype(bool)
    y_pred = df_eval["is_relevant_pred"].fillna(False).astype(bool)

    # -- Subproblema binario: is_relevant --
    tp = ((y_true) & (y_pred)).sum()
    fp = ((~y_true) & (y_pred)).sum()
    fn = ((y_true) & (~y_pred)).sum()
    tn = ((~y_true) & (~y_pred)).sum()
    prec_rel = tp / (tp + fp) if tp + fp > 0 else 0.0
    rec_rel  = tp / (tp + fn) if tp + fn > 0 else 0.0
    f1_rel   = 2 * prec_rel * rec_rel / (prec_rel + rec_rel) if prec_rel + rec_rel > 0 else 0.0
    acc_rel  = accuracy_score(y_true, y_pred)

    if verbose:
        if label:
            print(f"-- {label} --")
        print(f"\nis_relevant  Acc={acc_rel:.3f}  P={prec_rel:.3f}  R={rec_rel:.3f}  F1={f1_rel:.3f}")
        print(f"             TP={tp}  FP={fp}  FN={fn}  TN={tn}\n")

    # -- Multilabel N2: construir matrices binarias --
    Y_true = np.array([
        [1 if lbl in parse_labels(r["categories_gt"])   else 0 for lbl in N2]
        for _, r in df_eval.iterrows()
    ])
    Y_pred = np.array([
        [1 if lbl in parse_labels(r["categories_pred"]) else 0 for lbl in N2]
        for _, r in df_eval.iterrows()
    ])

    micro_f1   = f1_score(Y_true, Y_pred, average="micro",    zero_division=0)
    macro_f1   = f1_score(Y_true, Y_pred, average="macro",    zero_division=0)
    hl         = hamming_loss(Y_true, Y_pred)
    jaccard    = jaccard_score(Y_true, Y_pred, average="samples", zero_division=0)
    subset_acc = accuracy_score(Y_true, Y_pred)

    if verbose:
        print(f"N2 multilabel:")
        print(f"  Micro F1:      {micro_f1:.3f}")
        print(f"  Macro F1:      {macro_f1:.3f}")
        print(f"  Hamming Loss:  {hl:.4f}")
        print(f"  Jaccard:       {jaccard:.3f}")
        print(f"  Subset Acc:    {subset_acc:.3f}\n")

        print(f"{'Label':<10} {'P':>6} {'R':>6} {'F1':>6} {'Sup':>5}")
        print("-" * 35)
        for i, lbl in enumerate(N2):
            p2  = precision_score(Y_true[:, i], Y_pred[:, i], zero_division=0)
            r2  = recall_score   (Y_true[:, i], Y_pred[:, i], zero_division=0)
            f12 = f1_score       (Y_true[:, i], Y_pred[:, i], zero_division=0)
            print(f"{lbl:<10} {p2:>6.3f} {r2:>6.3f} {f12:>6.3f} {Y_true[:, i].sum():>5}")
        print("-" * 35)
        print(f"{'Macro':<10} {'':>13} {macro_f1:>6.3f}")

    card      = Y_true.sum(axis=1)
    exact_arr = (Y_true == Y_pred).all(axis=1)
    exact_ser = pd.Series(exact_arr, index=df_eval.index)

    if verbose:
        print("\nSubset Acc por cardinalidad:")
        for c, lbl_c in [(0, "card=0 (no relevante)"), (1, "card=1"), (2, "card=2"), (3, "card>=3")]:
            mask = (card >= c) if c == 3 else (card == c)
            if mask.sum() > 0:
                print(f"  {lbl_c:<22}: {exact_arr[mask].mean():.3f}  ({exact_arr[mask].sum()}/{mask.sum()})")
        conf = df_eval["confidence"].dropna()
        print(f"\nConfianza: media={conf.mean():.3f}  min={conf.min():.3f}  max={conf.max():.3f}")

    return {
        "is_rel_accuracy":  float(acc_rel),
        "is_rel_precision": float(prec_rel),
        "is_rel_recall":    float(rec_rel),
        "is_rel_f1":        float(f1_rel),
        "micro_f1":         float(micro_f1),
        "macro_f1":         float(macro_f1),
        "hamming_loss":     float(hl),
        "jaccard_samples":  float(jaccard),
        "subset_accuracy":  float(subset_acc),
        "exact":            exact_ser,
        "rel":              y_true,
    }

In [17]:
# Muestra los registros relevantes donde la predicción N2 no coincide con el GT.
def print_errors(df_eval, exact, rel, label="", n=None):
    errores = df_eval[~exact & rel]
    if n is not None:
        errores = errores.head(n)
    print(f"-- Errores N2 en relevantes{' · ' + label if label else ''} --")
    print(f"Total: {(~exact & rel).sum()}\n")
    for _, row in errores.iterrows():
        gt   = parse_labels(row["categories_gt"])
        pred = parse_labels(row["categories_pred"])
        print(f"ID {row['id']} | GT={sorted(gt)} | PRED={sorted(pred)}")
        print(f"  Falta: {sorted(gt - pred)} | Sobra: {sorted(pred - gt)}")
        print(f"  {str(row['description'])[:100]}...")
        print(f"  Razonamiento: {str(row.get('reasoning', ''))[:150]}")
        print()

In [18]:
df_b1_exp1 = pd.read_csv("../results/b1_exp1_baseline_qwen9b.csv")
df_eval_b1_1 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b1_exp1[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b1_1 = compute_metrics_B1(df_eval_b1_1, "Experimento B1-1 - Baseline")

-- Experimento B1-1 - Baseline --

is_relevant  Acc=0.818  P=0.818  R=1.000  F1=0.900
             TP=139  FP=31  FN=0  TN=0

N2 multilabel:
  Micro F1:      0.859
  Macro F1:      0.864
  Hamming Loss:  0.0235
  Jaccard:       0.675
  Subset Acc:    0.788

Label           P      R     F1   Sup
-----------------------------------
AGU_GEN     0.579  0.611  0.595    18
AGU_RIE     1.000  0.871  0.931    31
AGU_SND     0.739  0.895  0.810    19
AGU_ABS     0.909  0.952  0.930    21
AGU_IND     0.750  0.857  0.800     7
VIA_PEC     0.952  0.952  0.952    21
MON         1.000  0.900  0.947    10
ESP_NAT     0.417  1.000  0.588     5
RES         1.000  0.909  0.952    11
VER         1.000  1.000  1.000     7
PHD         1.000  1.000  1.000     2
-----------------------------------
Macro                     0.864

Subset Acc por cardinalidad:
  card=0 (no relevante) : 0.903  (28/31)
  card=1                : 0.766  (98/128)
  card=2                : 0.889  (8/9)
  card>=3               : 0.000  (0/2)

Confianza: media=0.939  min=0.000  max=1.000

In [19]:
print_errors(df_eval_b1_1, m_b1_1["exact"], m_b1_1["rel"], label="B1 Experimento 1 - Baseline")

-- Errores N2 en relevantes · B1 Experimento 1 - Baseline --
Total: 33

ID 0 | GT=['AGU_GEN'] | PRED=['AGU_SND']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública de resol...
  Razonamiento: El texto menciona explícitamente "concesión de aguas subterráneas" (señal AGU_SND), y por el término municipal de Bolaños de Calatrava en Ciudad Real

ID 4 | GT=['AGU_RIE'] | PRED=['AGU_GEN', 'AGU_RIE']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: La descripción menciona "concesión de un aprovechamiento de aguas subterráneas" (AGU_GEN) y específicamente indica "con destino a riego" (AGU_RIE), ad

ID 5 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de resolución del expediente de concesión ...
  Razonamiento: El texto menciona explícitamente "concesión de un aprovechamiento de aguas subterráneas" (señal de AGU_SND) y su "destino a riego" (señal de AGU_RIE).

ID 8 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: El texto menciona "concesión de un aprovechamiento de aguas subterráneas" y "modificación de características", lo que activa AGU_SND (sondeo/captación

ID 12 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. por el que se publica el inicio del trám...
  Razonamiento: La publicación es un anuncio sobre la creación de un área recreativa con zona de baño, pero no implica una concesión de aguas, uso específico del agua

ID 13 | GT=['AGU_GEN'] | PRED=['AGU_GEN', 'VIA_PEC']
  Falta: [] | Sobra: ['VIA_PEC']
  Anuncio de la Confederación Hidrográfica del Júcar, O.A. sobre información pública de una concesión ...
  Razonamiento: La descripción menciona "Concesión de aguas subterráneas" en Vinaròs, Castellón (CHJ/Júcar), lo que justifica AGU_GEN y cuenca_jucar. También cita "O.

ID 17 | GT=['AGU_IND'] | PRED=['AGU_GEN', 'AGU_IND']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública de la concesión de ...
  Razonamiento: El texto menciona explícitamente "aprovechamiento de aguas subterráneas" para "otros usos industriales" y que emite la Confederación Hidrográfica del

ID 20 | GT=['AGU_GEN'] | PRED=['AGU_SND']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública de resol...
  Razonamiento: El texto "resolución de otorgamiento de concesión de aguas subterráneas" activa la categoría AGU_SND (sondeo/captación puntual). La "Confederación Hid

ID 21 | GT=['AGU_GEN'] | PRED=['AGU_SND']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública de solic...
  Razonamiento: La descripción menciona explícitamente "concesión de aguas subterráneas" y "solicitación", lo que activa la categoría AGU_SND (sondeo/captación puntua

ID 24 | GT=['AGU_GEN'] | PRED=['AGU_ABS']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_ABS']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Ebro sobre información pública...
  Razonamiento: El texto menciona "aprovechamiento de aguas públicas subterráneas", lo que indica una concesión de abastecimiento (AGU_ABS). La referencia a la Confed

ID 26 | GT=['AGU_ABS', 'AGU_RIE', 'AGU_SND'] | PRED=['AGU_ABS', 'AGU_GEN', 'AGU_RIE']
  Falta: ['AGU_SND'] | Sobra: ['AGU_GEN']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: La descripción menciona explícitamente "riego de 0,02 ha" (señal para AGU_RIE/uso_agricola) y "abastecimiento" (señal para AGU_ABS/uso_urbano), así co

ID 28 | GT=['AGU_RIE'] | PRED=[]
  Falta: ['AGU_RIE'] | Sobra: []
  Anuncio de la Comunidad de Regantes de Ara sobre convocatoria de Asamblea General Ordinaria....
  Razonamiento: El texto describe una "convocatoria de Asamblea General Ordinaria" de una Comunidad de Regantes, que es un acto administrativo interno y organizativo

ID 29 | GT=['AGU_RIE'] | PRED=['AGU_GEN', 'AGU_RIE']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Comisaría de Aguas, de la Confederación Hidrográfica del Guadalquivir, de competencia ...
  Razonamiento: El texto menciona explícitamente "Concesión de uso de reutilización de aguas para un volumen anual... para uso Agropecuario - Regadío", lo cual activa

ID 30 | GT=['AGU_RIE'] | PRED=[]
  Falta: ['AGU_RIE'] | Sobra: []
  Anuncio de la Comunidad de Regantes de Las Vegas de Ejea de los Caballeros, Zaragoza, sobre convocat...
  Razonamiento: La publicación es un "Anuncio de la Comunidad de Regantes... sobre convocatoria de Junta". Aunque menciona a una comunidad de regantes, la acción es s

ID 33 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública de la concesión de ...
  Razonamiento: La descripción menciona explícitamente "aprovechamiento de aguas subterráneas para riego" que activa la categoría AGU_RIE y uso agrícola, además de id

ID 39 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: La publicación menciona explícitamente "procedimiento de extinción del derecho de una concesión de aguas públicas para riego", lo que activa la catego

ID 40 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de la resolución del expediente de concesi...
  Razonamiento: "Anuncio... resolución del expediente de concesión de un aprovechamiento de aguas subterráneas, de referencia C-0192/2023, con destino a riego en el t

ID 43 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  Resolución de 19 de marzo de 2025, de la Dirección General de Sostenibilidad, por la que se formula ...
  Razonamiento: La descripción menciona explícitamente "transformación en regadío de 16,0369 ha de olivar", lo que activa la categoría AGU_RIE (uso agrícola para rieg

ID 44 | GT=['AGU_RIE'] | PRED=[]
  Falta: ['AGU_RIE'] | Sobra: []
  Anuncio de la Comunidad de Regantes con Aguas Rodadas del Canal de Lodosa de Fréscano sobre convocat...
  Razonamiento: El texto describe una "convocatoria de Junta" de una comunidad de regantes, que es un acto de gobierno interno (Junta General) y no una concesión admi

ID 47 | GT=['AGU_RIE'] | PRED=[]
  Falta: ['AGU_RIE'] | Sobra: []
  Anuncio de la Comunidad de Regantes de Venta Micena sobre convocatoria de Junta....
  Razonamiento: La publicación es un anuncio de convocatoria de una Junta de la Comunidad de Regantes de Venta Micena, pero no detalla ninguna resolución, concesión o

ID 48 | GT=['AGU_ABS', 'AGU_IND', 'AGU_RIE'] | PRED=['AGU_ABS', 'AGU_GEN', 'AGU_IND', 'AGU_RIE']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: La publicación es un anuncio de la CHG Guadalquivir sobre una concesión múltiple: riego (5,8 ha) y abastecimiento industrial, activando AGU_GEN (uso n

ID 58 | GT=['AGU_ABS', 'AGU_SND'] | PRED=['AGU_GEN']
  Falta: ['AGU_ABS', 'AGU_SND'] | Sobra: ['AGU_GEN']
  RESOLUCIÓN de 11 de julio de 2024, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambien...
  Razonamiento: La resolución se refiere a un "Proyecto de captación de aguas subterráneas para abastecimiento hídrico", lo que indica una autorización de agua (AGU_G

ID 82 | GT=['AGU_IND'] | PRED=['AGU_IND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  Consejo Insular de Aguas de Lanzarote.- Anuncio de 25 de febrero de 2025, por el que se somete a inf...
  Razonamiento: El texto menciona explícitamente "aprovechamiento de agua para la mejora de la eficiencia mediante energía geotérmica" (uso energético, AGU_IND) y la

ID 83 | GT=['AGU_IND'] | PRED=['AGU_IND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  INFORMACIÓN pública relativa a la solicitud de autorización administrativa previa y autorización adm...
  Razonamiento: La publicación menciona explícitamente una "instalación de producción de energía eléctrica" y "central hidroeléctrica", lo que activa la categoría AGU

ID 84 | GT=['AGU_IND'] | PRED=[]
  Falta: ['AGU_IND'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: nan

ID 85 | GT=['VIA_PEC'] | PRED=['ESP_NAT', 'VIA_PEC']
  Falta: [] | Sobra: ['ESP_NAT']
  Vías pecuarias
– Resolución de 9 de enero de 2025, del Director General de Agricultura, Ganadería y ...
  Razonamiento: La descripción menciona explícitamente "vía pecuaria" y "Colada Galiana", activando la categoría VIA_PEC. Además, al ser una vía pecuaria en términos

ID 89 | GT=['VIA_PEC'] | PRED=[]
  Falta: ['VIA_PEC'] | Sobra: []
  Resolución de 04/02/2025, de la Delegación Provincial de Desarrollo Sostenible de Ciudad Real, por l...
  Razonamiento: El texto menciona "instalación solar fotovoltaica" y "ocupación de las fincas", pero no hace referencia a agua, vías pecuarias, montes protegidos, esp

ID 107 | GT=['MON'] | PRED=['AGU_IND', 'MON']
  Falta: [] | Sobra: ['AGU_IND']
  ANUNCIO del Instituto Aragonés de Gestión Ambiental, por el que se somete a información pública y co...
  Razonamiento: El texto menciona "dominio público forestal" y "monte de utilidad pública número 237", lo que activa la categoría MON. Además, se trata de una concesi

ID 114 | GT=['MON'] | PRED=[]
  Falta: ['MON'] | Sobra: []
  INFORMACIÓN pública relativa a la ocupación temporal de terrenos del monte de utilidad pública n.º 1...
  Razonamiento: nan

ID 129 | GT=['RES'] | PRED=[]
  Falta: ['RES'] | Sobra: []
  RESOLUCIÓN de 23 de diciembre de 2024, de la Delegación Territorial de Ávila, por la que se dicta in...
  Razonamiento: La publicación es una resolución de informe de impacto ambiental para una planta de tratamiento de residuos, pero NO corresponde a gestión de residuos

ID 136 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública sobre au...
  Razonamiento: La publicación describe una autorización para instalación de apicultura en dominio público hidráulico, no constituyendo una concesión o gestión del ag

ID 137 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: El texto describe la corta de árboles (chopos) en "dominio público hidráulico", pero la actividad es forestal/agricola y no gestión del agua como tal,

ID 151 | GT=['VER'] | PRED=['AGU_GEN', 'VER']
  Falta: [] | Sobra: ['AGU_GEN']
  Consejo Insular de Aguas de Tenerife.- Anuncio de 14 de enero de 2025, relativo a la solicitud de au...
  Razonamiento: La descripción contiene "tratamiento y vertido de las aguas residuales" (señal VER) y "aprovechamiento de aguas" para tratamiento de residuos sin uso

---

##  7. Experimento 2 - Prompt v2

**Problema**: el Exp 1 comete errores sistematicos en 6 patrones: (1) AGU_GEN se añade junto a etiquetas especificas de uso, (2) AGU_SND se activa por "aguas subterraneas" aunque el uso sea riego, (3) ESP_NAT se dispara por señales falsas (DG Sostenibilidad, Canarias, vias pecuarias), (4) convocatorias de comunidades de regantes clasificadas como irrelevantes, (5) autorizaciones de uso del DPH (apicultura, tala, obras) etiquetadas como VER, (6) VIA_PEC no detectada cuando solo aparece en el nombre del proyecto.

**Objetivo**: verificar si las reglas explicitas del prompt V2 corrigen estos patrones sin degradar el rendimiento general.

**Enfoque**: Qwen 3.5 9B · SYSTEM_PROMPT_B1_V2 · zero-shot · sin contexto N1.

**Resultados**: pendiente.

In [20]:
from clasificador.prompts_B1 import PROMPT_REGISTRY as PROMPT_REGISTRY_B1

agent_b1_v2 = build_agent(model, "v2", output_type=ClassifierOutputB1, prompt_registry=PROMPT_REGISTRY_B1)

df_b1_exp2 = await run_experiment(
    agent_b1_v2, df_anotado,
    use_n1_context=False, concurrency=1,
    output_path="../results/b1_exp2_promptv2_qwen9b.csv",
    desc="B1 Exp2 - Prompt v2",
)
df_b1_exp2.head(3)

  Reanudando: 170/170 registros ya clasificados

,id,bulletin,description,grupo_muestreo,is_relevant_gt,categories_gt,subcategories_gt,notas_anotador,is_relevant_pred,act_type_pred,categories_pred,subcategories_pred,confidence,reasoning,duration_s
0,0,boe,Anuncio de la Confederación Hidrográfica del G...,AGU_GEN,True,AGU_SND,cuenca_guadiana,NaN,True,anuncio,"[""AGU_SND""]","[""cuenca_guadiana"", ""uso_agricola""]",0.85,"El texto menciona explícitamente ""concesión de...",168.252
1,1,boe,Anuncio de formalización de contratos de: Pres...,AGU_GEN,False,NaN,NaN,NaN,False,anuncio,[],[],0.98,El texto describe un contrato de suministro y ...,61.812
2,2,boe,Anuncio de formalización de contratos de: Pres...,AGU_GEN,False,NaN,NaN,NaN,False,anuncio,[],[],1.00,La descripción corresponde a un anuncio de for...,69.076

In [21]:
df_b1_exp2 = pd.read_csv("../results/b1_exp2_promptv2_qwen9b.csv")
df_eval_b1_2 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b1_exp2[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b1_2 = compute_metrics_B1(df_eval_b1_2, "Experimento B1-2 - Prompt v2")

-- Experimento B1-2 - Prompt v2 --

is_relevant  Acc=0.818  P=0.818  R=1.000  F1=0.900
             TP=139  FP=31  FN=0  TN=0

N2 multilabel:
  Micro F1:      0.821
  Macro F1:      0.830
  Hamming Loss:  0.0299
  Jaccard:       0.658
  Subset Acc:    0.771

Label           P      R     F1   Sup
-----------------------------------
AGU_GEN     0.435  0.556  0.488    18
AGU_RIE     1.000  0.935  0.967    31
AGU_SND     0.682  0.789  0.732    19
AGU_ABS     0.818  0.857  0.837    21
AGU_IND     0.667  0.857  0.750     7
VIA_PEC     1.000  0.952  0.976    21
MON         0.900  0.900  0.900    10
ESP_NAT     0.556  1.000  0.714     5
RES         1.000  0.727  0.842    11
VER         1.000  0.857  0.923     7
PHD         1.000  1.000  1.000     2
-----------------------------------
Macro                     0.830

Subset Acc por cardinalidad:
  card=0 (no relevante) : 0.871  (27/31)
  card=1                : 0.766  (98/128)
  card=2                : 0.556  (5/9)
  card>=3               : 0.500  (1/2)

Confianza: media=0.936  min=0.500  max=1.000

In [22]:
print_errors(df_eval_b1_2, m_b1_2["exact"], m_b1_2["rel"], label="B1 Experimento 2 - Prompt v2")

-- Errores N2 en relevantes · B1 Experimento 2 - Prompt v2 --
Total: 35

ID 0 | GT=['AGU_GEN'] | PRED=['AGU_SND']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública de resol...
  Razonamiento: El texto menciona explícitamente "concesión de aguas subterráneas" para un uso en el término municipal, activando AGU_SND (sondeo/captación) y cuenca_

ID 3 | GT=['AGU_GEN'] | PRED=['AGU_SND']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Júcar, O.A. sobre información pública de una concesión ...
  Razonamiento: El texto es un "Anuncio de la Confederación Hidrográfica del Júcar" sobre "concesión de aguas subterráneas", lo que activa la categoría AGU_SND por se

ID 4 | GT=['AGU_RIE'] | PRED=['AGU_SND']
  Falta: ['AGU_RIE'] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: "El texto menciona explícitamente 'expediente de modificación... concesión de un aprovechamiento de aguas subterráneas' y el fin es 'con destino a rie

ID 7 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de acuerdo de información pública de la Comisaría de Aguas de la Confederación Hidrográfica ...
  Razonamiento: nan

ID 8 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: El texto menciona "concesión de un aprovechamiento de aguas subterráneas" para "riego", lo que activa AGU_RIE (uso agrícola). También aparece explícit

ID 15 | GT=['AGU_ABS'] | PRED=['AGU_GEN', 'ESP_NAT']
  Falta: ['AGU_ABS'] | Sobra: ['AGU_GEN', 'ESP_NAT']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. por el que se hace público el otorgamien...
  Razonamiento: El texto menciona explícitamente "otorgamiento de la concesión para aprovechamiento de... agua" con destino a "abastecimiento del núcleo de Porqueirós

ID 20 | GT=['AGU_GEN'] | PRED=['AGU_SND']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública de resol...
  Razonamiento: El texto describe una "resolución de otorgamiento de concesión de aguas subterráneas" lo que activa la categoría AGU_SND como objeto principal del exp

ID 21 | GT=['AGU_GEN'] | PRED=['AGU_SND']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Guadiana de sometimiento a información pública de solic...
  Razonamiento: El texto menciona "solicitud de concesión de aguas subterráneas" en Badajoz, lo que activa la categoría AGU_SND (sondeo/captación puntual). La cuenca

ID 22 | GT=['VER'] | PRED=['AGU_IND', 'VER']
  Falta: [] | Sobra: ['AGU_IND']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública de la autorización ...
  Razonamiento: El texto contiene "Anuncio de la Confederación Hidrográfica del Duero" y menciona "autorización de vertido de aguas residuales", lo que activa las cat

ID 24 | GT=['AGU_GEN'] | PRED=['AGU_ABS']
  Falta: ['AGU_GEN'] | Sobra: ['AGU_ABS']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Ebro sobre información pública...
  Razonamiento: La descripción menciona explícitamente "aprovechamiento de aguas públicas subterráneas", lo cual es una concesión de abastecimiento urbano (uso de agu

ID 26 | GT=['AGU_ABS', 'AGU_RIE', 'AGU_SND'] | PRED=['AGU_GEN', 'AGU_RIE']
  Falta: ['AGU_ABS', 'AGU_SND'] | Sobra: ['AGU_GEN']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: El texto menciona explícitamente "extinción del derecho de una concesión de aguas públicas para abastecimiento, riego" en Pozoblanco (Córdoba), activa

ID 29 | GT=['AGU_RIE'] | PRED=['AGU_GEN', 'AGU_RIE']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Comisaría de Aguas, de la Confederación Hidrográfica del Guadalquivir, de competencia ...
  Razonamiento: La descripción menciona explícitamente "concesión de uso de reutilización de aguas para un volumen anual... para uso Agropecuario - Regadío", lo que a

ID 35 | GT=['AGU_RIE', 'AGU_SND'] | PRED=['AGU_RIE']
  Falta: ['AGU_SND'] | Sobra: []
  Resolución de 16/01/2025, de la Delegación Provincial de Desarrollo Sostenible de Guadalajara, por l...
  Razonamiento: El texto describe una "Captación de aguas subterráneas para riego" (AGU_RIE). El término "riego" y el contexto de agricultura determinan "uso_agricola

ID 42 | GT=['AGU_RIE'] | PRED=['AGU_GEN']
  Falta: ['AGU_RIE'] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: El texto describe una concesión de aguas subterráneas para "riego" en Madrigal de las Altas Torres (Ávila), lo que indica uso agrícola y la pertenenci

ID 57 | GT=['AGU_RIE', 'AGU_SND'] | PRED=['AGU_ABS', 'AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_ABS']
  Resolución de 12/03/2025, de la Delegación Provincial de Desarrollo Sostenible de Toledo, por la que...
  Razonamiento: Texto explícito "Captación de aguas subterráneas" y "para riego de árboles variados", activando AGU_SND (captación), AGU_RIE (riego) y AGU_ABS (abaste

ID 58 | GT=['AGU_ABS', 'AGU_SND'] | PRED=['AGU_ABS']
  Falta: ['AGU_SND'] | Sobra: []
  RESOLUCIÓN de 11 de julio de 2024, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambien...
  Razonamiento: El texto menciona explícitamente "captación de aguas subterráneas para abastecimiento hídrico" (AGU_ABS, uso_urbano) y el término municipal de Vinaròs

ID 61 | GT=['AGU_ABS', 'AGU_SND'] | PRED=['AGU_ABS']
  Falta: ['AGU_SND'] | Sobra: []
  RESOLUCIÓN de 5 de febrero de 2025, de la Delegación Territorial de León, por la que se dicta el inf...
  Razonamiento: El texto especifica "abastecimiento de agua potable", lo cual es una señal directa para la categoría AGU_ABS. Además, el ayuntamiento promotor y la pr

ID 75 | GT=['AGU_ABS'] | PRED=['AGU_GEN']
  Falta: ['AGU_ABS'] | Sobra: ['AGU_GEN']
  Decreto 8/2025, de 18 de febrero, sobre declaración de urgencia de la ocupación de terrenos para eje...
  Razonamiento: El texto menciona "abastecimiento de agua para la eficiencia hídrica", lo que activa AGU_GEN (uso urbano implícito en abastecimiento) y cuenca_guadian

ID 80 | GT=['AGU_IND'] | PRED=['AGU_GEN', 'ESP_NAT']
  Falta: ['AGU_IND'] | Sobra: ['AGU_GEN', 'ESP_NAT']
  Anuncio del Área de Industria y Energía de la Subdelegación del Gobierno en Zaragoza por el que se s...
  Razonamiento: El texto menciona explícitamente "central hidroeléctrica reversible" y "aprovechamiento hidroeléctrico", lo que justifica la categoría AGU_GEN (como a

ID 82 | GT=['AGU_IND'] | PRED=['AGU_IND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  Consejo Insular de Aguas de Lanzarote.- Anuncio de 25 de febrero de 2025, por el que se somete a inf...
  Razonamiento: El texto menciona explícitamente "aprovechamiento de agua para la mejora de la eficiencia mediante energía geotérmica" lo que activa AGU_IND y uso_ene

ID 83 | GT=['AGU_IND'] | PRED=['AGU_IND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  INFORMACIÓN pública relativa a la solicitud de autorización administrativa previa y autorización adm...
  Razonamiento: El texto menciona explícitamente "central hidroeléctrica" y "producción de energía eléctrica", lo que activa las categorías AGU_IND (uso energético) y

ID 84 | GT=['AGU_IND'] | PRED=['AGU_GEN', 'AGU_IND']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: El texto menciona explícitamente "Consignación Hidrográfica del Miño-Sil" y uso industrial para refrigeración de hilo diamantado, activando las etique

ID 88 | GT=['VIA_PEC'] | PRED=[]
  Falta: ['VIA_PEC'] | Sobra: []
  INFORMACIÓN pública relativa a la ocupación temporal de terrenos en la vía pecuaria «Cañada de Extre...
  Razonamiento: nan

ID 89 | GT=['VIA_PEC'] | PRED=['AGU_GEN', 'VIA_PEC']
  Falta: [] | Sobra: ['AGU_GEN']
  Resolución de 04/02/2025, de la Delegación Provincial de Desarrollo Sostenible de Ciudad Real, por l...
  Razonamiento: La publicación menciona la ocupación de fincas por el proyecto fotovoltaico FV Braza Cordel (señalando "cordel" que activa VIA_PEC). Además, al tratar

ID 97 | GT=['VIA_PEC'] | PRED=['AGU_GEN', 'VIA_PEC']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio por el que se somete a información pública el pliego de condiciones que regirá en el expedie...
  Razonamiento: El texto menciona explícitamente "vía pecuaria denominada 'Colada de Vera'", activando la etiqueta VIA_PEC. Aunque es para suministro eléctrico ("acom

ID 105 | GT=['MON'] | PRED=['AGU_GEN']
  Falta: ['MON'] | Sobra: ['AGU_GEN']
  ANUNCIO del Instituto Aragonés de Gestión Ambiental, por el que se somete a información pública la r...
  Razonamiento: La publicación es una "notificación" o "anuncio" sobre renovación de concesión para ocupación temporal de terrenos en el "dominio público forestal", l

ID 111 | GT=['MON'] | PRED=['AGU_GEN', 'MON']
  Falta: [] | Sobra: ['AGU_GEN']
  Resolución de 09/12/2024, de la Dirección General de Medio Natural y Biodiversidad, por la que se ap...
  Razonamiento: La publicación menciona explícitamente "monte de utilidad pública" (MON) y "ocupación temporal en el monte". También se trata de una autorización de o

ID 122 | GT=['RES'] | PRED=[]
  Falta: ['RES'] | Sobra: []
  ANUNCIO del Director de Administración Ambiental, por el que se somete a información pública el proy...
  Razonamiento: El texto describe una gestión de residuos peligrosos y no peligrosos para la obtención de autorización ambiental única, sin mención alguna a uso de ag

ID 124 | GT=['RES'] | PRED=[]
  Falta: ['RES'] | Sobra: []
  Anuncio de 12/02/2025, de la Dirección General de Economía Circular y Agenda 2030, por el que se da ...
  Razonamiento: El texto trata sobre "tratamiento de residuos" y "almacenamiento de vehículos descontaminados", pero según las reglas, la gestión de residuos genérico

ID 129 | GT=['RES'] | PRED=[]
  Falta: ['RES'] | Sobra: []
  RESOLUCIÓN de 23 de diciembre de 2024, de la Delegación Territorial de Ávila, por la que se dicta in...
  Razonamiento: El texto describe una resolución sobre informe de impacto ambiental de una planta de tratamiento de residuos, pero la actividad económica (gestión de

ID 138 | GT=['VER'] | PRED=['AGU_GEN']
  Falta: ['VER'] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Tajo O.A. de la información pública de la solicitud de ...
  Razonamiento: El texto menciona "solicitud de autorización de vertido" pero sin especificar aguas residuales ni canon, por lo que se clasifica como AGU_GEN (uso del

ID 139 | GT=['VER'] | PRED=['AGU_SND', 'VER']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: El texto menciona "verdeo de aguas residuales" activando VER y también habla de "aprovechamiento de aguas subterráneas para sondeo" activando AGU_SND,

ID 140 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  ANUNCIO por el que se somete a información pública el expediente de obras de construcción del túnel ...
  Razonamiento: El texto describe "obras de construcción del túnel de Aginaga" y menciona "afección al dominio público hidráulico", pero no especifica ningún uso espe

ID 142 | GT=['VER'] | PRED=['AGU_GEN', 'VER']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Cantábrico, O.A. de informació...
  Razonamiento: El texto menciona "procedimiento de autorización de vertido" (etiqueta VER) y un uso mixto de alojamiento rural y centro de investigación (uso urbano

ID 144 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: El texto describe una autorización de corta de madera en dominio público hidráulico, pero no se refiere a un vertido de aguas residuales, gestión de r

---

##  8. Experimento 3 - Prompt v3

**Problema**: el Exp 2 sigue fallando en 8 patrones: AGU_SND spurious cuando no hay captacion/sondeo explicito, RES no detectado en IIA de plantas de residuos, VER con "solicitud de autorizacion de vertido" sin "aguas residuales", ESP_NAT falso en centrales y Canarias, AGU_GEN spurious coexistiendo con VIA_PEC/MON/VER, AGU_ABS con señales incompletas, y autorizaciones de uso de cauce sin vertido no reconocidas como AGU_GEN.

**Objetivo**: verificar si las 8 reglas refinadas del prompt V3 corrigen los patrones residuales sin degradar lo que ya funcionaba en V2.

**Enfoque**: Qwen 3.5 9B · SYSTEM_PROMPT_B1_V3 · zero-shot · sin contexto N1.

**Resultados**: pendiente.

In [23]:
agent_b1_v3 = build_agent(model, "v3", output_type=ClassifierOutputB1, prompt_registry=PROMPT_REGISTRY_B1)

df_b1_exp3 = await run_experiment(
    agent_b1_v3, df_anotado,
    use_n1_context=False, concurrency=1,
    output_path="../results/b1_exp3_promptv3_qwen9b.csv",
    desc="B1 Exp3 - Prompt v3",
)
df_b1_exp3.head(3)

  Reanudando: 170/170 registros ya clasificados

,id,bulletin,description,grupo_muestreo,is_relevant_gt,categories_gt,subcategories_gt,notas_anotador,is_relevant_pred,act_type_pred,categories_pred,subcategories_pred,confidence,reasoning,duration_s
0,0,boe,Anuncio de la Confederación Hidrográfica del G...,AGU_GEN,True,AGU_GEN,cuenca_guadiana,NaN,True,anuncio,"[""AGU_GEN""]","[""cuenca_guadiana""]",0.95,"El texto menciona ""Concesión de aguas subterrá...",149.189
1,1,boe,Anuncio de formalización de contratos de: Pres...,AGU_GEN,False,NaN,NaN,NaN,False,anuncio,[],[],1.00,La publicación es un anuncio de formalización ...,65.713
2,2,boe,Anuncio de formalización de contratos de: Pres...,AGU_GEN,False,NaN,NaN,NaN,False,anuncio,[],[],0.95,"La publicación es un ""Anuncio de formalización...",74.844

In [24]:
df_b1_exp3 = pd.read_csv("../results/b1_exp3_promptv3_qwen9b.csv")
df_eval_b1_3 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b1_exp3[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b1_3 = compute_metrics_B1(df_eval_b1_3, "Experimento B1-3 - Prompt v3")

-- Experimento B1-3 - Prompt v3 --

is_relevant  Acc=0.818  P=0.818  R=1.000  F1=0.900
             TP=139  FP=31  FN=0  TN=0

N2 multilabel:
  Micro F1:      0.852
  Macro F1:      0.842
  Hamming Loss:  0.0257
  Jaccard:       0.695
  Subset Acc:    0.794

Label           P      R     F1   Sup
-----------------------------------
AGU_GEN     0.500  0.722  0.591    18
AGU_RIE     1.000  0.903  0.949    31
AGU_SND     0.842  0.842  0.842    19
AGU_ABS     0.955  1.000  0.977    21
AGU_IND     0.667  0.857  0.750     7
VIA_PEC     1.000  0.952  0.976    21
MON         0.900  0.900  0.900    10
ESP_NAT     0.417  1.000  0.588     5
RES         0.846  1.000  0.917    11
VER         0.636  1.000  0.778     7
PHD         1.000  1.000  1.000     2
-----------------------------------
Macro                     0.842

Subset Acc por cardinalidad:
  card=0 (no relevante) : 0.871  (27/31)
  card=1                : 0.789  (101/128)
  card=2                : 0.778  (7/9)
  card>=3               : 0.000  (0/2)

Confianza: media=0.945  min=0.650  max=1.000

In [25]:
print_errors(df_eval_b1_3, m_b1_3["exact"], m_b1_3["rel"], label="B1 Experimento 3 - Prompt v3")

-- Errores N2 en relevantes · B1 Experimento 3 - Prompt v3 --
Total: 31

ID 4 | GT=['AGU_RIE'] | PRED=['AGU_GEN', 'AGU_RIE']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: El texto menciona "concesión de un aprovechamiento de aguas subterráneas" sin especificar uso explícito, lo que activa AGU_GEN por defecto residual. A

ID 7 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de acuerdo de información pública de la Comisaría de Aguas de la Confederación Hidrográfica ...
  Razonamiento: La publicación es un anuncio sobre "Aprovechamiento de pastos" en el término municipal de Puebla de Lillo (León), pero no se detectan categorías N2: n

ID 8 | GT=['AGU_RIE'] | PRED=['AGU_GEN']
  Falta: ['AGU_RIE'] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: El texto menciona "aprovechamiento de aguas subterráneas" sin usar las palabras clave específicas como "sondeo" o "captación", por lo que se clasifica

ID 10 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Tajo O.A. de la información pública de la solicitud de ...
  Razonamiento: El texto indica que es un "Anuncio de... información pública de la solicitud", no una resolución ni autorización final, por lo que no se clasifica com

ID 11 | GT=['AGU_SND'] | PRED=['AGU_GEN', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_GEN']
  Resolución de 11 de enero de 2025, de la Dirección General de Sostenibilidad, por la que se formula ...
  Razonamiento: El texto menciona explícitamente "sondeo para el aprovechamiento de aguas subterráneas" (señal AGU_SND) y se realiza en Cáceres, provincia pertenecien

ID 12 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. por el que se publica el inicio del trám...
  Razonamiento: El texto describe un anuncio sobre creación de área recreativa sin mención a categorías específicas como agua, vías pecuarias, montes o espacios natur

ID 15 | GT=['AGU_ABS'] | PRED=['AGU_ABS', 'VER']
  Falta: [] | Sobra: ['VER']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. por el que se hace público el otorgamien...
  Razonamiento: El texto menciona "abastecimiento del núcleo de Porqueirós", lo que activa la categoría AGU_ABS (abastecimiento municipal/agua potable) con subcategor

ID 16 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Cantábrico de información públ...
  Razonamiento: El texto es un anuncio de "información pública" sobre una concesión, pero no especifica el uso del agua (ni agrícola, urbano, industrial, ni energétic

ID 26 | GT=['AGU_ABS', 'AGU_RIE', 'AGU_SND'] | PRED=['AGU_ABS', 'AGU_GEN', 'AGU_RIE']
  Falta: ['AGU_SND'] | Sobra: ['AGU_GEN']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: El texto menciona explícitamente "abastecimiento" (AGU_ABS, uso urbano), "riego" (AGU_RIE, uso agrícola) y la Confederación Hidrográfica del Guadalqui

ID 35 | GT=['AGU_RIE', 'AGU_SND'] | PRED=['AGU_GEN', 'AGU_RIE']
  Falta: ['AGU_SND'] | Sobra: ['AGU_GEN']
  Resolución de 16/01/2025, de la Delegación Provincial de Desarrollo Sostenible de Guadalajara, por l...
  Razonamiento: La descripción menciona explícitamente "riego de carrascas truferas" (usando AGU_RIE) y sitúa el proyecto en Guadalajara (provincia perteneciente a la

ID 39 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: El texto menciona "concesión de aguas públicas para riego" y "procedimiento de extinción del derecho", lo que corresponde a AGU_RIE con subcategoría u

ID 42 | GT=['AGU_RIE'] | PRED=['AGU_GEN']
  Falta: ['AGU_RIE'] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: El texto indica "Concesión de aguas subterráneas" para "destino a riego" en "Madrigal de las Altas Torres (Ávila)", lo que activa AGU_GEN por la conce

ID 48 | GT=['AGU_ABS', 'AGU_IND', 'AGU_RIE'] | PRED=['AGU_ABS', 'AGU_IND', 'AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: El texto menciona explícitamente "riego de 5,8 ha" (AGU_RIE), "abastecimiento" (AGU_ABS), "uso industrial" (AGU_IND) y "captación en Sondeo" (AGU_SND)

ID 50 | GT=['AGU_SND'] | PRED=['AGU_SND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  RESOLUCIÓN de 17 de septiembre de 2024, de la Dirección General de Urbanismo, Paisaje y Evaluación A...
  Razonamiento: El texto menciona explícitamente "sondeo para captación de aguas subterráneas", activando la categoría AGU_SND. Al estar ubicado en Xaló (Alicante), c

ID 51 | GT=['AGU_SND'] | PRED=['AGU_GEN', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_GEN']
  Resolución de la directora general de Armonización Urbanística y Evaluación Ambiental por la cual se...
  Razonamiento: La descripción menciona explícitamente "captación de aguas subterráneas (sondeo)", lo que activa AGU_SND según las reglas. Como no se especifica el us

ID 53 | GT=['AGU_SND'] | PRED=['AGU_SND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  RESOLUCIÓN de 3 de febrero de 2025, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambie...
  Razonamiento: La descripción menciona explícitamente "Proyecto de sondeo para captación de aguas subterráneas", lo que activa la categoría AGU_SND y permite inferir

ID 56 | GT=['AGU_SND'] | PRED=['AGU_GEN', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_GEN']
  RESOLUCIÓN de 17 de enero de 2025, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambien...
  Razonamiento: El texto menciona explícitamente "sondeo para captación de aguas subterráneas" (activa AGU_SND) y se trata de una concesión en DPH con uso agrícola in

ID 57 | GT=['AGU_RIE', 'AGU_SND'] | PRED=['AGU_GEN', 'ESP_NAT']
  Falta: ['AGU_RIE', 'AGU_SND'] | Sobra: ['AGU_GEN', 'ESP_NAT']
  Resolución de 12/03/2025, de la Delegación Provincial de Desarrollo Sostenible de Toledo, por la que...
  Razonamiento: El texto menciona "captación de aguas subterráneas" en el expediente, lo que activa AGU_SND (concesión para uso) y usa explícito agrícola ("riego de á

ID 60 | GT=['AGU_SND'] | PRED=['AGU_SND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  RESOLUCIÓN de 26 de septiembre de 2024, de la Dirección General de Urbanismo, Paisaje y Evaluación A...
  Razonamiento: El texto menciona explícitamente "sondeo para captación de aguas subterráneas", activando AGU_SND, y el término "Informe de impacto ambiental" en el c

ID 63 | GT=['AGU_SND'] | PRED=['AGU_IND', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_IND']
  RESOLUCIÓN de 17 de enero de 2025, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambien...
  Razonamiento: El título indica "RESOLUCIÓN de 17 de enero de 2025... por la cual se formula un informe de impacto ambiental del proyecto de sondeo para la captación

ID 68 | GT=['AGU_ABS'] | PRED=['AGU_ABS', 'VER']
  Falta: [] | Sobra: ['VER']
  Anuncio sobre aprobación definitiva del Proyecto de mejora de la red de abastecimiento de aguas, alc...
  Razonamiento: El texto menciona "mejora de la red de abastecimiento de aguas", lo que indica AGU_ABS (abastecimiento). La inclusión de "alcantarillado y pluviales"

ID 76 | GT=['AGU_ABS'] | PRED=['AGU_ABS', 'VER']
  Falta: [] | Sobra: ['VER']
  Notificación colectiva de liquidaciones y anuncio de cobranza de la tasa por la prestación del servi...
  Razonamiento: El texto menciona explícitamente "suministro intermunicipal de agua potable" (AGU_ABS, uso_urbano) y la ubicación es Mallorca, que está en cuenca insu

ID 82 | GT=['AGU_IND'] | PRED=['AGU_GEN', 'AGU_SND', 'VER']
  Falta: ['AGU_IND'] | Sobra: ['AGU_GEN', 'AGU_SND', 'VER']
  Consejo Insular de Aguas de Lanzarote.- Anuncio de 25 de febrero de 2025, por el que se somete a inf...
  Razonamiento: El texto menciona "pozos de captación" (AGU_SND, uso energético), "vertdo de agua" (VER) y "aprovechamiento de agua" genérico para instalación geotérm

ID 83 | GT=['AGU_IND'] | PRED=['AGU_GEN', 'AGU_IND']
  Falta: [] | Sobra: ['AGU_GEN']
  INFORMACIÓN pública relativa a la solicitud de autorización administrativa previa y autorización adm...
  Razonamiento: La publicación trata sobre una instalación de energía fotovoltaica hibridada con central hidroeléctrica (señal clara para AGU_IND), autorizando el uso

ID 84 | GT=['AGU_IND'] | PRED=['AGU_IND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: El texto menciona explícitamente "aprovechamiento de agua" con "uso industrial (Refrigeración de hilo diamantado)", lo que activa AGU_IND y uso_indust

ID 89 | GT=['VIA_PEC'] | PRED=['AGU_IND', 'ESP_NAT']
  Falta: ['VIA_PEC'] | Sobra: ['AGU_IND', 'ESP_NAT']
  Resolución de 04/02/2025, de la Delegación Provincial de Desarrollo Sostenible de Ciudad Real, por l...
  Razonamiento: La publicación es una resolución sobre la ocupación de fincas por un proyecto fotovoltaico (FV Braza Cordel), lo que indica uso energético [AGU_IND, s

ID 105 | GT=['MON'] | PRED=['AGU_GEN', 'MON']
  Falta: [] | Sobra: ['AGU_GEN']
  ANUNCIO del Instituto Aragonés de Gestión Ambiental, por el que se somete a información pública la r...
  Razonamiento: El texto menciona explícitamente "monte de utilidad pública" y "dominio público forestal", activando la categoría MON. Además, se trata de una ocupaci

ID 110 | GT=['MON'] | PRED=[]
  Falta: ['MON'] | Sobra: []
  Resolución de 11/11/2024, de la Dirección General de Medio Natural y Biodiversidad, por la que se ap...
  Razonamiento: El texto describe una "ocupación temporal en el monte de utilidad pública" para instalar línea eléctrica, pero no menciona explícitamente "monte de ut

ID 111 | GT=['MON'] | PRED=['ESP_NAT', 'MON']
  Falta: [] | Sobra: ['ESP_NAT']
  Resolución de 09/12/2024, de la Dirección General de Medio Natural y Biodiversidad, por la que se ap...
  Razonamiento: El texto menciona explícitamente "monte de utilidad pública", activando la categoría MON, y sitúa el monte en el catálogo de la provincia de Albacete,

ID 140 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  ANUNCIO por el que se somete a información pública el expediente de obras de construcción del túnel ...
  Razonamiento: La descripción indica "afectación al dominio público hidráulico" y a "zona de policía de cauces", pero no describe ninguna concesión, autorización ni

ID 144 | GT=['AGU_GEN'] | PRED=['AGU_GEN', 'MON']
  Falta: [] | Sobra: ['MON']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: El texto menciona "dominio público hidráulico" y autorización para corta de árboles (señal AGU_GEN). Además, aparece explícitamente "monte de utilidad

---

##  9. Experimento 4 - Prompt v4

**Problema**: el Exp 3 introduce 4 regresiones: (1) ESP_NAT se dispara por nombres de organismos que contienen "Paisaje", "Medio Natural" o "Desarrollo Sostenible", (2) VER se dispara por "alcantarillado" como infraestructura, (3) AGU_RIE no se detecta cuando la fuente es "aguas subterraneas" sin captacion explicita, (4) AGU_GEN no reconocido para aprovechamientos en DPH sin concesion de agua.

**Objetivo**: verificar si las 4 reglas correctoras del prompt V4 eliminan estas regresiones sin introducir nuevos errores.

**Enfoque**: Qwen 3.5 9B · SYSTEM_PROMPT_B1_V4 · zero-shot · sin contexto N1.

**Resultados**: pendiente.

In [26]:
agent_b1_v4 = build_agent(model, "v4", output_type=ClassifierOutputB1, prompt_registry=PROMPT_REGISTRY_B1)

df_b1_exp4 = await run_experiment(
    agent_b1_v4, df_anotado,
    use_n1_context=False, concurrency=1,
    output_path="../results/b1_exp4_promptv4_qwen9b.csv",
    desc="B1 Exp4 - Prompt v4",
)
df_b1_exp4.head(3)

  Reanudando: 44/170 registros ya clasificados

B1 Exp4 - Prompt v4:   1%|          | 1/126 [01:49<3:48:00, 109.45s/it]

  [ERROR] UnexpectedModelBehavior: Exceeded maximum output retries (1)

B1 Exp4 - Prompt v4: 100%|██████████| 126/126 [2:14:39<00:00, 64.12s/it]

Tiempo: 8078.5s total  |  64.11s/item  |  126 items

,id,bulletin,description,grupo_muestreo,is_relevant_gt,categories_gt,subcategories_gt,notas_anotador,is_relevant_pred,act_type_pred,categories_pred,subcategories_pred,confidence,reasoning,duration_s
0,0,boe,Anuncio de la Confederación Hidrográfica del G...,AGU_GEN,True,AGU_GEN,cuenca_guadiana,NaN,True,anuncio,"[""AGU_GEN""]",[],0.55,"La descripción menciona ""concesión de aguas su...",249.912
1,1,boe,Anuncio de formalización de contratos de: Pres...,AGU_GEN,False,NaN,NaN,NaN,False,anuncio,[],[],1.00,Es un anuncio de formalización de contrato de ...,65.593
2,2,boe,Anuncio de formalización de contratos de: Pres...,AGU_GEN,False,NaN,NaN,NaN,False,anuncio,[],[],1.00,"La publicación se refiere a un ""Contrato de se...",69.597

In [27]:
df_b1_exp4 = pd.read_csv("../results/b1_exp4_promptv4_qwen9b.csv")
df_eval_b1_4 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b1_exp4[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b1_4 = compute_metrics_B1(df_eval_b1_4, "Experimento B1-4 - Prompt v4")

-- Experimento B1-4 - Prompt v4 --

is_relevant  Acc=0.818  P=0.818  R=1.000  F1=0.900
             TP=139  FP=31  FN=0  TN=0

N2 multilabel:
  Micro F1:      0.879
  Macro F1:      0.895
  Hamming Loss:  0.0198
  Jaccard:       0.699
  Subset Acc:    0.824

Label           P      R     F1   Sup
-----------------------------------
AGU_GEN     0.577  0.833  0.682    18
AGU_RIE     1.000  0.871  0.931    31
AGU_SND     0.850  0.895  0.872    19
AGU_ABS     0.944  0.810  0.872    21
AGU_IND     1.000  1.000  1.000     7
VIA_PEC     1.000  0.952  0.976    21
MON         0.800  0.800  0.800    10
ESP_NAT     0.714  1.000  0.833     5
RES         0.917  1.000  0.957    11
VER         1.000  0.857  0.923     7
PHD         1.000  1.000  1.000     2
-----------------------------------
Macro                     0.895

Subset Acc por cardinalidad:
  card=0 (no relevante) : 0.935  (29/31)
  card=1                : 0.812  (104/128)
  card=2                : 0.778  (7/9)
  card>=3               : 0.000  (0/2)

Confianza: media=0.945  min=0.550  max=1.000

In [28]:
print_errors(df_eval_b1_4, m_b1_4["exact"], m_b1_4["rel"], label="B1 Experimento 4 - Prompt v4")

-- Errores N2 en relevantes · B1 Experimento 4 - Prompt v4 --
Total: 28

ID 8 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: Se menciona "expediente de modificación de características de concesión" y el texto incluye explícitamente "concesión de un aprovechamiento de aguas s

ID 9 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Tajo O.A. de la resolución de la solicitud de una conce...
  Razonamiento: El texto describe una "concesión de aguas en el término municipal de Utande (Guadalajara)" pero no especifica ningún uso concreto del agua. Según las

ID 12 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. por el que se publica el inicio del trám...
  Razonamiento: La publicación trata sobre un área recreativa con zona de baño, sin mención a concesión de aguas, usos del agua en DPH, ni protección ambiental especí

ID 14 | GT=['AGU_ABS', 'AGU_RIE'] | PRED=['AGU_RIE']
  Falta: ['AGU_ABS'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública del expediente de m...
  Razonamiento: El texto menciona "con destino a riego" que activa la categoría AGU_RIE y "abastecimiento" indicando uso urbano, aunque según las reglas críticas solo

ID 15 | GT=['AGU_ABS'] | PRED=['AGU_GEN', 'MON']
  Falta: ['AGU_ABS'] | Sobra: ['AGU_GEN', 'MON']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. por el que se hace público el otorgamien...
  Razonamiento: El texto indica "otorgamiento de la concesión" (acto administrativo) con "destino a abastecimiento del núcleo" y para "extinción de incendios", activa

ID 17 | GT=['AGU_IND'] | PRED=['AGU_GEN', 'AGU_IND']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública de la concesión de ...
  Razonamiento: El texto menciona explícitamente "concesión de un aprovechamiento de aguas subterráneas para otros usos industriales" y la fuente es "Confederación Hi

ID 22 | GT=['VER'] | PRED=[]
  Falta: ['VER'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública de la autorización ...
  Razonamiento: nan

ID 26 | GT=['AGU_ABS', 'AGU_RIE', 'AGU_SND'] | PRED=['AGU_GEN']
  Falta: ['AGU_ABS', 'AGU_RIE', 'AGU_SND'] | Sobra: ['AGU_GEN']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: El texto menciona explícitamente "extinción del derecho de una concesión de aguas públicas para abastecimiento, riego" (activa AGU_GEN como categoría

ID 33 | GT=['AGU_RIE'] | PRED=[]
  Falta: ['AGU_RIE'] | Sobra: []
  Anuncio de la Confederación Hidrográfica del Duero, O.A., de información pública de la concesión de ...
  Razonamiento: nan

ID 35 | GT=['AGU_RIE', 'AGU_SND'] | PRED=[]
  Falta: ['AGU_RIE', 'AGU_SND'] | Sobra: []
  Resolución de 16/01/2025, de la Delegación Provincial de Desarrollo Sostenible de Guadalajara, por l...
  Razonamiento: nan

ID 39 | GT=['AGU_RIE'] | PRED=['AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: La publicación menciona "concesión de aguas públicas para riego" (etiqueta AGU_RIE) y también indica "captación en Sondeo" (etiqueta AGU_SND). Además,

ID 44 | GT=['AGU_RIE'] | PRED=[]
  Falta: ['AGU_RIE'] | Sobra: []
  Anuncio de la Comunidad de Regantes con Aguas Rodadas del Canal de Lodosa de Fréscano sobre convocat...
  Razonamiento: nan

ID 48 | GT=['AGU_ABS', 'AGU_IND', 'AGU_RIE'] | PRED=['AGU_ABS', 'AGU_IND', 'AGU_RIE', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_SND']
  Anuncio de la Comisaría de Aguas de la Confederación Hidrográfica del Guadalquivir de información pú...
  Razonamiento: El texto incluye explícitamente "con destino a riego" y "riego de 5,8 ha", activando AGU_RIE; "abastecimiento" activa AGU_ABS; "uso industrial" activa

ID 50 | GT=['AGU_SND'] | PRED=['AGU_GEN', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_GEN']
  RESOLUCIÓN de 17 de septiembre de 2024, de la Dirección General de Urbanismo, Paisaje y Evaluación A...
  Razonamiento: El texto contiene explícitamente "sondeo para captación de aguas subterráneas" (AGU_SND), y dado que Xaló es un municipio de Alicante, la provincia de

ID 56 | GT=['AGU_SND'] | PRED=['AGU_GEN', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_GEN']
  RESOLUCIÓN de 17 de enero de 2025, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambien...
  Razonamiento: El texto contiene explícitamente "sondeo para captación de aguas subterráneas", lo que activa la categoría AGU_SND según la regla 4, ya que los términ

ID 59 | GT=['AGU_SND'] | PRED=['AGU_ABS', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_ABS']
  RESOLUCIÓN de 17 de septiembre de 2024, de la Dirección General de Urbanismo, Paisaje y Evaluación A...
  Razonamiento: La publicación es una Resolución de la Dirección General de Urbanismo, Paisaje y Evaluación Ambiental sobre un informe de impacto ambiental para un "p

ID 62 | GT=['AGU_SND'] | PRED=['AGU_GEN', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_GEN']
  RESOLUCIÓN de 21 de octubre de 2024, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambi...
  Razonamiento: El texto menciona "proyecto de sondeo para la captación de aguas subterráneas" que activa AGU_SND y el informe de impacto ambiental sugiere un uso agr

ID 63 | GT=['AGU_SND'] | PRED=['AGU_GEN', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_GEN']
  RESOLUCIÓN de 17 de enero de 2025, de la Dirección General de Urbanismo, Paisaje y Evaluación Ambien...
  Razonamiento: El texto menciona "sondeo para la captación de aguas subterráneas", lo cual activa las categorías AGU_SND y AGU_GEN según las reglas críticas. Además,

ID 64 | GT=['AGU_SND'] | PRED=['AGU_GEN', 'AGU_SND']
  Falta: [] | Sobra: ['AGU_GEN']
  ANUNCIO del Servicio Territorial de Industria, Comercio y Economía de León, relativo a la aprobación...
  Razonamiento: El texto menciona explícitamente "sondeo para captación de aguas subterráneas" lo que activa la categoría AGU_SND (sondeo/captación). La ausencia de m

ID 70 | GT=['AGU_ABS'] | PRED=[]
  Falta: ['AGU_ABS'] | Sobra: []
  Secretaría General Técnica.- Anuncio por el que se hace pública la Resolución de 14 de febrero de 20...
  Razonamiento: La publicación es un anuncio de resolución sobre tarifas del servicio público de abastecimiento, pero el acto administrativo no pertenece al dominio d

ID 82 | GT=['AGU_IND'] | PRED=['AGU_IND', 'ESP_NAT']
  Falta: [] | Sobra: ['ESP_NAT']
  Consejo Insular de Aguas de Lanzarote.- Anuncio de 25 de febrero de 2025, por el que se somete a inf...
  Razonamiento: La publicación menciona "aprovechamiento de agua para la mejora de la eficiencia mediante energía geotérmica" lo que activa AGU_IND con uso_energetico

ID 83 | GT=['AGU_IND'] | PRED=['AGU_GEN', 'AGU_IND']
  Falta: [] | Sobra: ['AGU_GEN']
  INFORMACIÓN pública relativa a la solicitud de autorización administrativa previa y autorización adm...
  Razonamiento: El texto menciona una instalación fotovoltaica hibridada con central hidroeléctrica existente y la solicitud de autorización, lo que activa AGU_GEN (p

ID 84 | GT=['AGU_IND'] | PRED=['AGU_GEN', 'AGU_IND']
  Falta: [] | Sobra: ['AGU_GEN']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: El texto menciona explícitamente "con destino a uso industrial" por lo que se activa la categoría AGU_IND. Además, la mención de "Extinción del aprove

ID 89 | GT=['VIA_PEC'] | PRED=[]
  Falta: ['VIA_PEC'] | Sobra: []
  Resolución de 04/02/2025, de la Delegación Provincial de Desarrollo Sostenible de Ciudad Real, por l...
  Razonamiento: La publicación es una resolución sobre la ocupación de fincas para una instalación solar fotovoltaica (FV Braza Cordel). No existe ninguna mención a a

ID 107 | GT=['MON'] | PRED=['ESP_NAT']
  Falta: ['MON'] | Sobra: ['ESP_NAT']
  ANUNCIO del Instituto Aragonés de Gestión Ambiental, por el que se somete a información pública y co...
  Razonamiento: Se clasifica como ESP_NAT porque el texto se refiere al dominio público forestal ("monte de utilidad pública") y a una concesión para ocupación tempor

ID 110 | GT=['MON'] | PRED=[]
  Falta: ['MON'] | Sobra: []
  Resolución de 11/11/2024, de la Dirección General de Medio Natural y Biodiversidad, por la que se ap...
  Razonamiento: La publicación se refiere a "ocupación de monte de utilidad pública" y línea eléctrica, pero según las reglas MON requiere el término explícito "monte

ID 140 | GT=['AGU_GEN'] | PRED=[]
  Falta: ['AGU_GEN'] | Sobra: []
  ANUNCIO por el que se somete a información pública el expediente de obras de construcción del túnel ...
  Razonamiento: El texto menciona "afuición al dominio público hidráulico" pero se refiere a una obra de construcción de túnel (infraestructura vial) sin conceder ni

ID 144 | GT=['AGU_GEN'] | PRED=['AGU_GEN', 'MON']
  Falta: [] | Sobra: ['MON']
  Anuncio de la Confederación Hidrográfica del Miño-Sil, O.A. de información pública del expediente de...
  Razonamiento: El texto menciona "corta de... en dominio público hidráulico" y refiere árboles (alisos, sauces, fresnos) típicos de bosques o zonas forestales, lo cu

---

##  10. Experimento 5 - Prompt v5 (few-shot)

**Problema**: algunos patrones persisten a pesar de las reglas explicitas: el modelo no generaliza correctamente AGU_RIE vs AGU_SND/GEN, ESP_NAT con organismos ambientales, y VER con infraestructura de saneamiento.

**Objetivo**: comprobar si 5 ejemplos few-shot quirurgicos sobre los errores mas persistentes mejoran el rendimiento respecto a V4.

**Enfoque**: Qwen 3.5 9B · SYSTEM_PROMPT_B1_V5 (V4 + 5 ejemplos) · few-shot · sin contexto N1.

**Resultados**: pendiente.

In [29]:
agent_b1_v5 = build_agent(model, "v5", output_type=ClassifierOutputB1, prompt_registry=PROMPT_REGISTRY_B1)

df_b1_exp5 = await run_experiment(
    agent_b1_v5, df_anotado,
    use_n1_context=False, concurrency=1,
    output_path="../results/b1_exp5_promptv5_qwen9b.csv",
    desc="B1 Exp5 - Prompt v5 few-shot",
)
df_b1_exp5.head(3)

B1 Exp5 - Prompt v5 few-shot:   4%|▍         | 7/170 [07:35<2:55:22, 64.56s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:   5%|▌         | 9/170 [10:04<3:07:16, 69.79s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:   6%|▌         | 10/170 [11:23<3:13:48, 72.68s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:   7%|▋         | 12/170 [13:49<3:11:18, 72.65s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:   8%|▊         | 13/170 [15:05<3:12:41, 73.64s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:   8%|▊         | 14/170 [16:58<3:42:27, 85.56s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:   9%|▉         | 15/170 [18:01<3:23:39, 78.83s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:   9%|▉         | 16/170 [18:53<3:01:36, 70.76s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  11%|█         | 18/170 [20:52<2:44:33, 64.96s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  12%|█▏        | 20/170 [22:55<2:38:28, 63.39s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  12%|█▏        | 21/170 [23:59<2:37:20, 63.36s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  13%|█▎        | 22/170 [25:05<2:38:46, 64.37s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  14%|█▍        | 24/170 [26:59<2:27:28, 60.61s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  16%|█▌        | 27/170 [29:42<2:14:47, 56.55s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  18%|█▊        | 30/170 [32:22<2:06:56, 54.41s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  20%|██        | 34/170 [36:07<2:08:55, 56.88s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  21%|██        | 36/170 [38:02<2:07:25, 57.06s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  22%|██▏       | 37/170 [39:13<2:16:02, 61.37s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  23%|██▎       | 39/170 [41:04<2:07:39, 58.47s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  24%|██▎       | 40/170 [42:00<2:05:11, 57.78s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  25%|██▍       | 42/170 [43:50<1:58:49, 55.70s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  26%|██▌       | 44/170 [45:36<1:53:39, 54.12s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  28%|██▊       | 47/170 [48:19<1:52:17, 54.78s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  29%|██▉       | 49/170 [50:04<1:47:33, 53.33s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  30%|███       | 51/170 [51:45<1:42:59, 51.93s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  31%|███       | 52/170 [52:41<1:44:48, 53.29s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  31%|███       | 53/170 [53:34<1:43:51, 53.26s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  32%|███▏      | 54/170 [54:26<1:41:59, 52.75s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  32%|███▏      | 55/170 [55:18<1:41:01, 52.70s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  33%|███▎      | 56/170 [56:12<1:40:25, 52.85s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  34%|███▎      | 57/170 [57:02<1:37:59, 52.03s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  34%|███▍      | 58/170 [57:59<1:39:53, 53.51s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  35%|███▍      | 59/170 [58:48<1:36:55, 52.40s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  35%|███▌      | 60/170 [59:40<1:35:49, 52.27s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  36%|███▌      | 61/170 [1:00:31<1:34:17, 51.90s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  36%|███▋      | 62/170 [1:01:24<1:33:43, 52.07s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  37%|███▋      | 63/170 [1:02:16<1:32:58, 52.13s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  38%|███▊      | 64/170 [1:03:08<1:31:46, 51.95s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  38%|███▊      | 65/170 [1:04:06<1:34:28, 53.99s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  40%|████      | 68/170 [1:06:50<1:31:07, 53.61s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  42%|████▏     | 71/170 [1:09:37<1:29:09, 54.04s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  44%|████▎     | 74/170 [1:12:58<1:42:04, 63.79s/it]

  [ERROR] UnexpectedModelBehavior: Model token limit (provider default) exceeded before any response was generated. Increase the `max_tokens` model setting, or simplify the prompt to result in a shorter response that will fit within the limit.

B1 Exp5 - Prompt v5 few-shot:  45%|████▍     | 76/170 [1:16:23<1:34:28, 60.31s/it]

CancelledError:

  [ERROR] ClosedResourceError:

In [ ]:
df_b1_exp5 = pd.read_csv("../results/b1_exp5_promptv5_qwen9b.csv")
df_eval_b1_5 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b1_exp5[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b1_5 = compute_metrics_B1(df_eval_b1_5, "Experimento B1-5 - Prompt v5 few-shot")

In [ ]:
print_errors(df_eval_b1_5, m_b1_5["exact"], m_b1_5["rel"], label="B1 Experimento 5 - Prompt v5 few-shot")

---

##  11. Comparativa de modelos - Gemma 4B con prompt V4

**Problema**: todos los experimentos anteriores usan Qwen 3.5 9B. No sabemos si el prompt es transferible a modelos mas pequeños y rapidos.

**Objetivo**: comprobar si Gemma 4 4B con el mejor prompt (V4) alcanza un rendimiento comparable al 9B, midiendo transferibilidad y coste en tiempo.

**Enfoque**: Gemma 4 4B · SYSTEM_PROMPT_B1_V4 · zero-shot · sin contexto N1.

**Resultados**: pendiente.

In [ ]:
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider as OAIProvider

# Cargar gemma-4-e4b-it en LM Studio antes de ejecutar
model_gemma = OpenAIChatModel("gemma-4-e4b-it", provider=OAIProvider(base_url="http://localhost:1234/v1", api_key="lm-studio"))
agent_b1_gemma = build_agent(model_gemma, "v4", output_type=ClassifierOutputB1, prompt_registry=PROMPT_REGISTRY_B1)

df_b1_gemma = await run_experiment(
    agent_b1_gemma, df_anotado,
    use_n1_context=False, concurrency=1,
    output_path="../results/b1_exp_gemma4b_v4.csv",
    desc="B1 Gemma4B - Prompt v4",
)
df_b1_gemma.head(3)

In [ ]:
df_b1_gemma = pd.read_csv("../results/b1_exp_gemma4b_v4.csv")
df_eval_b1_gemma = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b1_gemma[["description","is_relevant_pred","act_type_pred","categories_pred",
                 "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b1_gemma = compute_metrics_B1(df_eval_b1_gemma, "B1 Gemma 4B - Prompt v4")

In [ ]:
print_errors(df_eval_b1_gemma, m_b1_gemma["exact"], m_b1_gemma["rel"], label="B1 Gemma 4B - Prompt v4")

---

##  10. Tabla resumen - Comparativa de experimentos B1

In [ ]:
experimentos_cfg_B1 = [
    ("B1 Exp1 - Baseline V1",    "Qwen 3.5 9B", "Zero-shot", "../results/b1_exp1_baseline_qwen9b.csv"),
    ("B1 Exp2 - Prompt V2",      "Qwen 3.5 9B", "Zero-shot", "../results/b1_exp2_promptv2_qwen9b.csv"),
    ("B1 Exp3 - Prompt V3",      "Qwen 3.5 9B", "Zero-shot", "../results/b1_exp3_promptv3_qwen9b.csv"),
    ("B1 Exp4 - Prompt V4",      "Qwen 3.5 9B", "Zero-shot", "../results/b1_exp4_promptv4_qwen9b.csv"),
    ("B1 Exp5 - Gemma 4B V4",    "Gemma 4 4B",  "Zero-shot", "../results/b1_exp_gemma4b_v4.csv"),
]

rows_b1 = []
metrics_list_b1 = []
for nombre, modelo, config, path in experimentos_cfg_B1:
    df_r = pd.read_csv(path)
    df_e = df_anotado[["id","is_relevant_gt","categories_gt","description"]].merge(
        df_r[["description","is_relevant_pred","categories_pred","confidence","duration_s"]],
        on="description", how="left"
    )
    m = compute_metrics_B1(df_e, verbose=False)
    metrics_list_b1.append({"Experimento": nombre, **m})
    rows_b1.append({
        "Experimento": nombre,
        "Modelo":      modelo,
        "Config":      config,
        "is_rel_f1":       m["is_rel_f1"],
        "micro_f1":        m["micro_f1"],
        "macro_f1":        m["macro_f1"],
        "hamming_loss":    m["hamming_loss"],
        "jaccard_samples": m["jaccard_samples"],
        "subset_accuracy": m["subset_accuracy"],
        "mean_duration_s": round(df_r["duration_s"].mean(), 2) if "duration_s" in df_r.columns else None,
        "total_duration_s": round(df_r["duration_s"].sum(), 0) if "duration_s" in df_r.columns else None,
    })

df_summary_b1 = pd.DataFrame(rows_b1)

# Formatear para display
df_display_b1 = df_summary_b1.copy()
df_display_b1.columns = [
    "Experimento", "Modelo", "Config",
    "is_rel F1", "Micro F1", "Macro F1", "Hamming", "Jaccard", "Subset Acc",
    "s/item", "Total (s)",
]
display(df_display_b1.set_index("Experimento"))