# B2 — Clasificador Urbanístico

Notebook de clasificación taxonómica para publicaciones del dominio urbanístico.
Sigue la misma arquitectura incremental que B0 (ambiental-energético) y B1 (hídrico y natural).

In [1]:
import os
import html
import re
import json
import asyncio
from pathlib import Path

import pandas as pd
import numpy as np

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    hamming_loss,
    jaccard_score,
)
from sklearn.preprocessing import MultiLabelBinarizer

from dotenv import find_dotenv, load_dotenv
from pydantic_ai import Agent

SEED = 29092025

load_dotenv(find_dotenv())

True

In [2]:
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider

LM_STUDIO_MODEL = "qwen/qwen3.5-9b"

model = OpenAIChatModel(
    LM_STUDIO_MODEL,
    provider=OpenAIProvider(
        base_url="http://localhost:1234/v1",
        api_key="lm-studio",
    ),
)

In [3]:
import httpx

try:
    r = httpx.get("http://localhost:1234/v1/models", timeout=3)
    modelos = [m["id"] for m in r.json()["data"]]
    assert LM_STUDIO_MODEL in modelos, f"{LM_STUDIO_MODEL} no está cargado en LM Studio"
    print(f"OK: {LM_STUDIO_MODEL} listo  |  otros: {[m for m in modelos if m != LM_STUDIO_MODEL]}")
except httpx.ConnectError:
    raise RuntimeError("LM Studio no responde - arrancar el servidor antes de continuar")

OK: qwen/qwen3.5-9b listo  |  otros: ['google/gemma-4-e4b', 'gemma-4-e4b-it', 'google/gemma-3n-e4b', 'gemma-4-e2b-it', 'google/gemma-3-4b', 'text-embedding-nomic-embed-text-v1.5']

## 1. Schema B2

In [4]:
from clasificador.schema_B2 import (
    ActType, CategoryTypeB2, SubcategoryTypeB2, ClassifierOutputB2
)

In [5]:
ejemplo_valido = ClassifierOutputB2(
    is_relevant=True,
    act_type=ActType.RESOLUCION,
    categories=[CategoryTypeB2.LIC_URB],
    subcategories=[SubcategoryTypeB2.USO_RUSTICO, SubcategoryTypeB2.USO_ENERGETICO],
    confidence=0.95,
    reasoning="'autorización de uso excepcional de suelo rústico' → LIC_URB + uso_rustico. 'planta solar fotovoltaica' → uso_energetico.",
)
print("Ejemplo válido:")
print(ejemplo_valido.model_dump_json(indent=2))

print("\nViolación de invariante:")
try:
    ClassifierOutputB2(
        is_relevant=False, act_type=ActType.RESOLUCION,
        categories=[CategoryTypeB2.PGOU], subcategories=[],
        confidence=0.5, reasoning="Prueba.",
    )
except Exception as e:
    print(f"  ValidationError -> {e.errors()[0]['msg']}")

Ejemplo válido:
{
  "is_relevant": true,
  "act_type": "resolución",
  "categories": [
    "LIC_URB"
  ],
  "subcategories": [
    "uso_rustico",
    "uso_energetico"
  ],
  "confidence": 0.95,
  "reasoning": "'autorización de uso excepcional de suelo rústico' → LIC_URB + uso_rustico. 'planta solar fotovoltaica' → uso_energetico."
}

Violación de invariante:
  ValidationError -> Value error, is_relevant=False con categories != []

## 2. Exploración del corpus B2

In [6]:
from clasificador.agent import get_ambito, inferir_act_type

PATH_PARQUET = "../data/raw/silver_official_gazettes_2025_Q1.parquet"
df = pd.read_parquet(PATH_PARQUET)
df["description"] = df["description"].apply(lambda x: html.unescape(str(x)) if pd.notna(x) else x)
print(f"Corpus total: {len(df):,} registros | Columnas: {list(df.columns)}")

Corpus total: 65,201 registros | Columnas: ['id', 'pdf_link', 'expediente', 'promotor', 'proyecto', 'description', 'tipo', 'clean_id', 'bulletin', 'provincias', 'municipios', 'raw_scraped_timestamp', 'raw_scraped_year_month', 'scraped_timestamp', 'scraped_year_month', 'publication_timestamp', 'publication_type', 'contains_aau', 'proxy_pdf_link', 'ambito', 'rango']

In [7]:
df["act_type_n1"] = df.apply(
    lambda r: inferir_act_type(str(r["description"]), str(r["bulletin"])).value, axis=1
)

keywords_dominio_B2 = [
    "plan general de ordenación", "pgou", "poum", "pom de ", "pxom", "normas subsidiarias",
    "normas urbanísticas municipales", "plan parcial", "plan especial", "estudio de detalle",
    "modificación puntual", "proyecto de urbanización", "reparcelación",
    "licencia urbanística", "autorización de uso excepcional", "calificación urbanística",
    "actuación específica de interés público", "declaración de interés comunitario",
    "declaración de utilidad e interés social",
]
mask_b2 = df["description"].str.lower().str.contains("|".join(keywords_dominio_B2), na=False)
df_b2 = df[mask_b2].copy()
print(f"Universo B2 estimado: {len(df_b2):,} registros ({len(df_b2)/len(df)*100:.2f}% del corpus)")
print(f"\nDistribución por boletín (top 10):")
print(df_b2["bulletin"].value_counts().head(10).to_string())
print(f"\nDistribución N1 en universo B2:")
print(df_b2["act_type_n1"].value_counts().head(8).to_string())

Universo B2 estimado: 1,687 registros (2.59% del corpus)

Distribución por boletín (top 10):
bulletin
bocyl    442
docm     202
bon      185
dogv     159
dogc     102
doe       78
dog       64
bopa      59
bocm      58
borm      56

Distribución N1 en universo B2:
act_type_n1
anuncio                623
información_pública    338
aprobación             259
resolución             211
acuerdo                 95
orden                   50
edicto                  41
corrección_errores      26

## 3. Ground truth — Muestreo estratificado

In [8]:
keywords_B2 = {
    "PGOU":     ["plan general de ordenación", "pgou", "poum", "pom de ", "pxom",
                 "pgom", "pgm de ", "normas subsidiarias",
                 "normas urbanísticas municipales", " num "],
    "PLAN_ESP": ["plan parcial", "plan especial", "estudio de detalle"],
    "MOD_PUN":  ["modificación puntual", "modificación del plan general",
                 "modificación de las normas subsidiarias",
                 "modificación de las normas urbanísticas"],
    "PROY_URB": ["proyecto de urbanización", "reparcelación", "parcelación",
                 "unidad de ejecución"],
    "LIC_URB":  ["licencia urbanística", "autorización de uso excepcional",
                 "calificación urbanística",
                 "actuación específica de interés público",
                 "usos y actividades admisibles en suelo rústico",
                 "autorización de actividades en suelo no urbanizable"],
    "DIC_INT":  ["declaración de interés comunitario",
                 "declaración de utilidad e interés social",
                 "uso de interés general"],
}

cuotas_B2 = {
    "LIC_URB": 30, "MOD_PUN": 25, "PLAN_ESP": 25,
    "PGOU": 25, "PROY_URB": 15, "DIC_INT": 5,
}
N_MULTILABEL_FV = 10
N_NEGATIVOS     = 15

desc_lower = df["description"].str.lower()
print(f"{'Label':<12} {'Pool':>8} {'Cuota':>7} {'Estado':>12}")
print("-" * 44)
for label, kws in keywords_B2.items():
    mask = desc_lower.str.contains("|".join(kws), na=False)
    pool = mask.sum()
    cuota = cuotas_B2.get(label, 0)
    estado = "OK" if pool >= cuota else f"REDUCIDA a {min(cuota, pool)}"
    print(f"{label:<12} {pool:>8,} {cuota:>7} {estado:>12}")

Label            Pool   Cuota       Estado
--------------------------------------------
PGOU              461      25           OK
PLAN_ESP          630      25           OK
MOD_PUN           445      25           OK
PROY_URB          231      15           OK
LIC_URB           391      30           OK
DIC_INT            30       5           OK

In [9]:
desc_lower = df["description"].str.lower()
sampled_ids = set()
frames = []

# Keywords para detectar renovables en suelo rústico (multilabel B2+B0)
kws_fv_rustico = ["fotovoltaica", "eólica", "aerogenerador", "solar"]
kws_rustico    = ["suelo rústico", "suelo no urbanizable", "uso excepcional"]

# 1. Muestra estratificada por categoría
for label, kws in keywords_B2.items():
    mask = desc_lower.str.contains("|".join(kws), na=False)
    mask = mask & ~df.index.isin(sampled_ids)
    pool = df[mask]
    n = min(cuotas_B2.get(label, 0), len(pool))
    if n == 0:
        print(f"  {label:<12} SKIP (pool vacío)")
        continue
    sample = pool.sample(n, random_state=SEED).copy()
    sample["grupo_muestreo"] = label
    sampled_ids.update(sample.index.tolist())
    frames.append(sample)
    print(f"  {label:<12} pool={len(pool):>5,}  sampled={n}")

# 2. Multilabel FV en suelo rústico (LIC_URB solar/eólica)
mask_fv = (
    desc_lower.str.contains("|".join(kws_fv_rustico), na=False)
    & desc_lower.str.contains("|".join(kws_rustico), na=False)
    & ~df.index.isin(sampled_ids)
)
pool_fv = df[mask_fv]
n_fv = min(N_MULTILABEL_FV, len(pool_fv))
if n_fv > 0:
    sample_fv = pool_fv.sample(n_fv, random_state=SEED).copy()
    sample_fv["grupo_muestreo"] = "MULTILABEL_FV"
    sampled_ids.update(sample_fv.index.tolist())
    frames.append(sample_fv)
    print(f"  {'MULTILABEL_FV':<12} pool={len(pool_fv):>5,}  sampled={n_fv}")

# 3. Negativos
all_kws_b2 = [kw for kws in keywords_B2.values() for kw in kws]
mask_neg = (
    ~desc_lower.str.contains("|".join(all_kws_b2), na=False)
    & ~df.index.isin(sampled_ids)
)
pool_neg = df[mask_neg]
negativos = pool_neg.sample(N_NEGATIVOS, random_state=SEED).copy()
negativos["grupo_muestreo"] = "NEGATIVO"
frames.append(negativos)

df_muestreo = pd.concat(frames, ignore_index=True)
df_muestreo["id"] = range(len(df_muestreo))
print(f"\nTotal muestreado: {len(df_muestreo)} registros")
print(df_muestreo["grupo_muestreo"].value_counts().to_string())

  PGOU         pool=  461  sampled=25
  PLAN_ESP     pool=  629  sampled=25
  MOD_PUN      pool=  433  sampled=25
  PROY_URB     pool=  225  sampled=15
  LIC_URB      pool=  390  sampled=30
  DIC_INT      pool=   30  sampled=5
  MULTILABEL_FV pool=   74  sampled=10

Total muestreado: 150 registros
grupo_muestreo
LIC_URB          30
PGOU             25
PLAN_ESP         25
MOD_PUN          25
PROY_URB         15
NEGATIVO         15
MULTILABEL_FV    10
DIC_INT           5

In [10]:
print("Validación del muestreo - 3 ejemplos por grupo:\n")
for grupo in df_muestreo["grupo_muestreo"].unique():
    muestra = df_muestreo[df_muestreo["grupo_muestreo"] == grupo].head(3)
    print(f"--- {grupo} ---")
    for _, row in muestra.iterrows():
        desc = str(row["description"])[:130].replace("\n", " ")
        bul  = str(row.get("bulletin", "?")).upper()
        print(f"  [{bul}] {desc}")
    print()

Validación del muestreo - 3 ejemplos por grupo:

--- PGOU ---
  [BOJA] Resolución de 16 de enero de 2025, de la Delegación Territorial de Fomento, Articulación del Territorio y Vivienda en Málaga, por
  [BOCM] Plan general de urbanismo – Acuerdo de 12 de marzo de 2025, del Consejo de Gobierno, por el que se aprueba definitivamente la Deci
  [DOCM] Anuncio de 28/01/2025, del Ayuntamiento de Villar de Olalla (Cuenca), sobre exposición pública del Plan Especial de Reforma Interi

--- PLAN_ESP ---
  [BOPA] Resolución de 3 de febrero de 2025, de la Consejería de Transición Ecológica, Industria y Desarrollo Económico, por la que se form
  [BON] Aprobación definitiva del Plan Especial de Actuación Urbana de las unidades UE-9 y UE-10
  [BOCYL] INFORMACIÓN pública relativa a la aprobación inicial del estudio de detalle, promovido por «Decoración Muebles Cagigal, S.A.», par

--- MOD_PUN ---
  [BOCYL] ACUERDO de 19 de diciembre de 2024, del Pleno del Ayuntamiento de Palencia, por el que se aprueba definitivamente la modificación
  [BOC] Informe Ambiental Estratégico de la Modificación Puntual 1/2022 de las Normas Subsidiarias de planeamiento de Riotuerto.
  [DOCM] Anuncio de 14/01/2025, del Ayuntamiento de Ciudad Real, sobre información pública de la Modificación Puntual número 4 del Plan Par

--- PROY_URB ---
  [BOCYL] INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rústico, para la ejecución del proyecto de
  [DOE] Anuncio de 19 de febrero de 2025 sobre aprobación inicial del Proyecto de Urbanización que afecta al Sector Urbanizable SUB-1 de l
  [BOJA] Anuncio de 14 de marzo de 2025, de la Dirección General de Ordenación del Territorio, Urbanismo y Agenda Urbana, por el que se not

--- LIC_URB ---
  [DOGC] Anuncio por el que se somete a información pública la solicitud de autorización administrativa previa, autorización administrativa
  [DOGC] Anuncio por el que se somete a información pública la solicitud de autorización administrativa previa, autorización administrativa
  [BOCYL] ORDEN MAV/239/2025, de 11 de marzo, por la que se aprueba definitivamente la modificación del Plan General de Ordenación Urbana de

--- DIC_INT ---
  [DOGV] ANUNCIO por el que se somete a información pública la declaración de interés comunitario para una atribución de uso y aprovechamie
  [DOGV] ANUNCIO de la solicitud de declaración de interés comunitario de regularización de actividad industrial en suelo no urbanizable de
  [DOGV] ANUNCI de la declaración de interés comunitario para una atribución de uso y aprovechamiento en suelo no urbanizable relativa a la

--- MULTILABEL_FV ---
  [BOCYL] CORRECCIÓN de errores del anuncio de información pública relativa a la solicitud de autorización de uso excepcional de suelo rústi
  [BOCYL] INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rústico, licencia de obras y licencia ambi
  [DOCM] Anuncio de 01/03/2025, del Ayuntamiento de Albacete, de la Gerencia Municipal de Urbanismo y Vivienda, sobre información pública d

--- NEGATIVO ---
  [DOGC] Resolución PRE/175/2025, de 21 de enero, por la que se da publicidad al deslinde entre los términos municipales de Sort y de Rialp
  [BOJA] Anuncio de 21 de enero de 2025, de la Delegación Territorial de Agricultura, Pesca, Agua y Desarrollo Rural en Jaén, por el que se
  [DOG] RESOLUCIÓN de 24 de enero de 2025, del Departamento Territorial de Lugo, por la que se concede la autorización administrativa prev

In [11]:
PATH_MUESTREO = "../data/ground_truth/ground_truth_B2_muestreo.csv"
Path(PATH_MUESTREO).parent.mkdir(parents=True, exist_ok=True)

df_muestreo["is_relevant_gt"]   = ""
df_muestreo["categories_gt"]    = ""
df_muestreo["subcategories_gt"] = ""
df_muestreo["notas_anotador"]   = ""

df_muestreo[["id","bulletin","description","grupo_muestreo",
             "is_relevant_gt","categories_gt","subcategories_gt","notas_anotador"]].to_csv(
    PATH_MUESTREO, index=False
)
print(f"Guardado: {PATH_MUESTREO}  ({len(df_muestreo)} registros)")
print("Siguiente paso: anotar manualmente las columnas is_relevant_gt, categories_gt, subcategories_gt")

Guardado: ../data/ground_truth/ground_truth_B2_muestreo.csv  (150 registros)
Siguiente paso: anotar manualmente las columnas is_relevant_gt, categories_gt, subcategories_gt

## 4. Agente base

In [12]:
from clasificador.schema_B2 import ClassifierOutputB2
from clasificador.prompts_B2 import PROMPT_REGISTRY_B2
from clasificador.agent import build_agent, run_experiment

In [13]:
agent_b2_v1 = build_agent(
    model, "v1",
    output_type=ClassifierOutputB2,
    prompt_registry=PROMPT_REGISTRY_B2,
)

# Casos cualitativos representativos del dominio B2
casos_b2 = [
    ("Anuncio del Ayuntamiento de Torrelodones por el que se somete a información pública la aprobación inicial del Plan General de Ordenación Urbana.", "bocm"),
    ("Resolución de la Consejería de Urbanismo por la que se aprueba definitivamente la modificación puntual número 5 del Plan General Municipal de Cuenca.", "docm"),
    ("Anuncio de información pública relativo a la solicitud de autorización de uso excepcional de suelo rústico para instalación solar fotovoltaica de 2 MW en Villarrobledo (Albacete).", "docm"),
    ("Anuncio del Ajuntament de Girona pel qual se sotmet a informació pública l'aprovació inicial del Pla d'Ordenació Urbanística Municipal (POUM) de Girona.", "dogc"),
    ("Resolución de la Universidad Complutense de Madrid por la que se aprueba la modificación del plan de estudios del Grado en Medicina conforme al Real Decreto 822/2021.", "boe"),
]

for desc, bul in casos_b2:
    print(f"\n[{bul.upper()}] {desc[:80]}...")
    # result = await agent_b2_v1.run(f"Boletín: {bul.upper()}\n\nDescripción: {desc}")
    # print(result.output.model_dump_json(indent=2))

[BOCM] Anuncio del Ayuntamiento de Torrelodones por el que se somete a información públ...

[DOCM] Resolución de la Consejería de Urbanismo por la que se aprueba definitivamente l...

[DOCM] Anuncio de información pública relativo a la solicitud de autorización de uso ex...

[DOGC] Anuncio del Ajuntament de Girona pel qual se sotmet a informació pública l'aprov...

[BOE] Resolución de la Universidad Complutense de Madrid por la que se aprueba la modi...

## 5. Funciones de evaluación B2

In [14]:
def parse_labels(value) -> set:
    """Convierte cualquier representación de etiquetas a un set de strings."""
    if pd.isna(value) or str(value).strip() in ("", "nan"):
        return set()
    s = str(value).strip()
    if s.startswith("["):
        try:
            items = json.loads(s)
            return {str(i).strip('"') for i in items if i}
        except json.JSONDecodeError:
            pass
    return {v.strip().strip('"') for v in s.split(",") if v.strip()}

In [15]:
def compute_metrics_B2(df_eval, label="", verbose=True):
    """
    Calcula métricas multilabel para el clasificador B2.
    Columnas esperadas: is_relevant_gt, categories_gt, is_relevant_pred, categories_pred.
    """
    ALL_CATS_B2 = [e.value for e in CategoryTypeB2]
    mlb = MultiLabelBinarizer(classes=ALL_CATS_B2)
    mlb.fit([ALL_CATS_B2])

    gt_labels   = [parse_labels(v) & set(ALL_CATS_B2) for v in df_eval["categories_gt"]]
    pred_labels = [parse_labels(v) & set(ALL_CATS_B2) for v in df_eval["categories_pred"]]
    Y    = mlb.transform(gt_labels)
    Yhat = mlb.transform(pred_labels)

    is_rel_gt   = df_eval["is_relevant_gt"].astype(bool)
    is_rel_pred = df_eval["is_relevant_pred"].astype(bool)

    exact = pd.Series([set(g) == set(p) for g, p in zip(gt_labels, pred_labels)])
    rel   = is_rel_gt

    metrics = {
        "is_rel_accuracy":  round(accuracy_score(is_rel_gt, is_rel_pred), 4),
        "is_rel_precision": round(precision_score(is_rel_gt, is_rel_pred, zero_division=0), 4),
        "is_rel_recall":    round(recall_score(is_rel_gt, is_rel_pred, zero_division=0), 4),
        "is_rel_f1":        round(f1_score(is_rel_gt, is_rel_pred, zero_division=0), 4),
        "micro_f1":         round(f1_score(Y, Yhat, average="micro", zero_division=0), 4),
        "macro_f1":         round(f1_score(Y, Yhat, average="macro", zero_division=0), 4),
        "hamming_loss":     round(hamming_loss(Y, Yhat), 4),
        "jaccard_samples":  round(jaccard_score(Y, Yhat, average="samples", zero_division=0), 4),
        "subset_accuracy":  round(accuracy_score(Y, Yhat), 4),
        "exact": exact,
        "rel":   rel,
    }

    if verbose:
        title = f"-- {label} --" if label else "-- Métricas B2 --"
        print(f"\n{title}\n")
        tp = int((is_rel_gt & is_rel_pred).sum())
        fp = int((~is_rel_gt & is_rel_pred).sum())
        fn = int((is_rel_gt & ~is_rel_pred).sum())
        tn = int((~is_rel_gt & ~is_rel_pred).sum())
        print(f"is_relevant  Acc={metrics['is_rel_accuracy']:.3f}  P={metrics['is_rel_precision']:.3f}  "
              f"R={metrics['is_rel_recall']:.3f}  F1={metrics['is_rel_f1']:.3f}")
        print(f"             TP={tp}  FP={fp}  FN={fn}  TN={tn}\n")
        print(f"N2 multilabel:")
        print(f"  Micro F1:      {metrics['micro_f1']:.3f}")
        print(f"  Macro F1:      {metrics['macro_f1']:.3f}")
        print(f"  Hamming Loss:  {metrics['hamming_loss']:.4f}")
        print(f"  Jaccard:       {metrics['jaccard_samples']:.3f}")
        print(f"  Subset Acc:    {metrics['subset_accuracy']:.3f}\n")
        f1s = f1_score(Y, Yhat, average=None, zero_division=0)
        sups = Y.sum(axis=0)
        print(f"  {'Label':<12} {'P':>6} {'R':>6} {'F1':>6} {'Sup':>5}")
        print(f"  {'-'*37}")
        for i, cat in enumerate(ALL_CATS_B2):
            prec = precision_score(Y[:, i], Yhat[:, i], zero_division=0)
            rec  = recall_score(Y[:, i], Yhat[:, i], zero_division=0)
            print(f"  {cat:<12} {prec:>6.3f} {rec:>6.3f} {f1s[i]:>6.3f} {int(sups[i]):>5}")
        print(f"  {'-'*37}")
        print(f"  {'Macro':<12} {'':>6} {'':>6} {metrics['macro_f1']:>6.3f}\n")

        cards = [len(g) for g in gt_labels]
        print(f"  Subset Acc por cardinalidad:")
        for card in [0, 1, 2]:
            idx = [i for i, c in enumerate(cards) if c == card]
            if idx:
                acc = accuracy_score(Y[idx], Yhat[idx])
                print(f"    card={card} ({'no relevante' if card == 0 else str(card)}) : {acc:.3f}  ({int(acc*len(idx))}/{len(idx)})")
        idx3 = [i for i, c in enumerate(cards) if c >= 3]
        if idx3:
            acc3 = accuracy_score(Y[idx3], Yhat[idx3])
            print(f"    card>=3               : {acc3:.3f}  ({int(acc3*len(idx3))}/{len(idx3)})")

        conf = df_eval.get("confidence", pd.Series(dtype=float))
        if conf.notna().any():
            print(f"\n  Confianza: media={conf.mean():.3f}  min={conf.min():.3f}  max={conf.max():.3f}")

    return metrics

In [16]:
def print_errors_B2(df_eval, exact, rel, label="", n=None):
    errores = df_eval[~exact & rel]
    if n is not None:
        errores = errores.head(n)
    lbl = f" · {label}" if label else ""
    print(f"\n-- Errores N2 en relevantes{lbl} --")
    print(f"Total: {len(errores)}\n")
    for _, row in errores.iterrows():
        gt   = sorted(parse_labels(row["categories_gt"]))
        pred = sorted(parse_labels(row["categories_pred"]))
        falta = sorted(set(gt) - set(pred))
        sobra = sorted(set(pred) - set(gt))
        desc  = str(row["description"])[:90].replace("\n", " ")
        razon = str(row.get("reasoning", "")).replace("\n", " ")[:120]
        print(f"ID {row['id']} | GT={gt} | PRED={pred}")
        print(f"  Falta: {falta} | Sobra: {sobra}")
        print(f"  {desc}...")
        print(f"  Razonamiento: {razon}")
        print()

---

##  6. Experimento 1 - Baseline zero-shot

**Problema**: No existe un clasificador para el dominio urbanístico. Necesitamos una línea base que mida el rendimiento zero-shot antes de cualquier optimización.

**Objetivo**: Establecer el Macro-F1 de referencia con el prompt mínimo operativo (V1) y detectar los patrones de error sistematicos que guiarán la mejora del prompt.

**Enfoque**: Qwen 3.5 9B · SYSTEM_PROMPT_B2_V1 · zero-shot · sin contexto N1.

**Resultados**: pendiente.

In [17]:
df_anotado = pd.read_csv("../data/ground_truth/ground_truth_B2_anotado.csv")
df_anotado_run = df_anotado[df_anotado["is_relevant_gt"].notna()].copy()

df_b2_exp1 = await run_experiment(
    agent_b2_v1, df_anotado_run,
    use_n1_context=False, concurrency=1,
    output_path="../results/b2_exp1_baseline_qwen9b.csv",
    desc="B2 Exp1 - Baseline V1",
)
df_b2_exp1.head(3)

  Reanudando: 149/150 registros ya clasificados

,id,bulletin,description,grupo_muestreo,is_relevant_gt,categories_gt,subcategories_gt,notas_anotador,is_relevant_pred,act_type_pred,categories_pred,subcategories_pred,confidence,reasoning,duration_s
0,0,boja,"Resolución de 16 de enero de 2025, de la Deleg...",PGOU,True,MOD_PUN,fase_definitiva,Publicacion registro Modificacion PGOU Mijas,True,orden,"[""PGOU"", ""MOD_PUN""]",[],0.95,La descripción menciona explícitamente «Modifi...,114.957
1,1,bocm,Plan general de urbanismo\n– Acuerdo de 12 de ...,PGOU,True,MOD_PUN,fase_definitiva,Decimoctava Modificacion Puntual PGOU Getafe,True,acuerdo,"[""PGOU"", ""MOD_PUN""]","[""fase_definitiva""]",0.98,"La descripción menciona explícitamente ""Plan g...",64.742
2,2,docm,"Anuncio de 28/01/2025, del Ayuntamiento de Vil...",PGOU,True,PLAN_ESP,fase_ip,PERIM exposicion publica - Plan Especial Refor...,True,anuncio,"[""PGOU"", ""PLAN_ESP""]","[""fase_ip""]",0.95,"El texto menciona ""Normas Subsidiarias"" que en...",71.333

In [18]:
df_b2_exp1 = pd.read_csv("../results/b2_exp1_baseline_qwen9b.csv")
df_eval_b2_1 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b2_exp1[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b2_1 = compute_metrics_B2(df_eval_b2_1, "Experimento B2-1 - Baseline")
print_errors_B2(df_eval_b2_1, m_b2_1["exact"], m_b2_1["rel"], label="B2 Experimento 1 - Baseline")

-- Experimento B2-1 - Baseline --

is_relevant  Acc=0.908  P=0.908  R=1.000  F1=0.952
             TP=138  FP=14  FN=0  TN=0

N2 multilabel:
  Micro F1:      0.693
  Macro F1:      0.626
  Hamming Loss:  0.1206
  Jaccard:       0.532
  Subset Acc:    0.355

  Label             P      R     F1   Sup
  -------------------------------------
  PGOU          0.060  1.000  0.113     3
  PLAN_ESP      0.714  1.000  0.833    25
  MOD_PUN       0.977  0.977  0.977    44
  PROY_URB      0.833  0.652  0.732    23
  LIC_URB       0.767  0.825  0.795    40
  DIC_INT       0.179  1.000  0.303     5
  -------------------------------------
  Macro                       0.626

  Subset Acc por cardinalidad:
    card=0 (no relevante) : 0.929  (13/14)
    card=1 (1) : 0.287  (39/136)
    card=2 (2) : 1.000  (2/2)

  Confianza: media=0.958  min=0.650  max=1.000

-- Errores N2 en relevantes · B2 Experimento 1 - Baseline --
Total: 97

ID 0 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Resolución de 16 de enero de 2025, de la Delegación Territorial de Fomento, Articulación d...
  Razonamiento: La descripción menciona explícitamente «Modificación del Plan General de Ordenación Urbana (PGOU)» y «normas urbanística

ID 1 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Plan general de urbanismo – Acuerdo de 12 de marzo de 2025, del Consejo de Gobierno, por e...
  Razonamiento: La descripción menciona explícitamente "Plan general de urbanismo" y "Decimoctava Modificación Puntual del Plan General

ID 2 | GT=['PLAN_ESP'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 28/01/2025, del Ayuntamiento de Villar de Olalla (Cuenca), sobre exposición púb...
  Razonamiento: El texto menciona "Normas Subsidiarias" que en Cuenca funciona como instrumento regulatorio equivalente a PGOU, y además

ID 3 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 27/12/2024, del Ayuntamiento de Albacete, de la Gerencia Municipal de Urbanismo...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación Urbana" (PGOU) y una "alternativa técnica de Programa de Ac

ID 4 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Viceconsejería de Planificación Territorial y Reto Demográfico.- Anuncio por el que se hac...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación" (PGOU) y "Modificación Menor", lo que activa las categoría

ID 5 | GT=['PROY_URB'] | PRED=['PGOU']
  Falta: ['PROY_URB'] | Sobra: ['PGOU']
  Anuncio de 20 de febrero de 2025 sobre aprobación inicial del Programa de Ejecución de la ...
  Razonamiento: La descripción menciona explícitamente "Aprobación inicial" (subcategoría fase_inicial) y "Programa de Ejecución" refere

ID 6 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Anuncio sobre aprobación inicial de la modificación puntual del Plan general de ordenación...
  Razonamiento: La descripción menciona explícitamente "Plan general de ordenación municipal" (PGOU), "modificación puntual" (MOD_PUN),

ID 7 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  EDICTO de aprobación del informe ambiental y territorial estratégico, por el procedimiento...
  Razonamiento: El texto contiene explícitamente las categorías PGOU y MOD_PUN. Se cita 'Plan general de ordenación urbana' (PGOU) y 'mo

ID 8 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Informe Ambiental Estratégico de la Modificación Puntual número 1, del Plan General de Ord...
  Razonamiento: El texto menciona explícitamente "Modificación Puntual número 1" (MOD_PUN) y "Plan General de Ordenación Urbana" (PGOU).

ID 9 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO de 6 de noviembre de 2024, por el que se somete a información pública la aprobació...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación" (PGOU) y "Modificación Menor del Plan General" (MOD_PUN).

ID 10 | GT=['MOD_PUN'] | PRED=['LIC_URB', 'MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['LIC_URB', 'PGOU']
  ANUNCIO del Acuerdo de 25 de noviembre de 2024, de la Junta de Gobierno Local, del informe...
  Razonamiento: El texto menciona explícitamente "modificación puntual del Plan general de ordenación urbana" (categorías PGOU y MOD_PUN

ID 11 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']
  INFORMACIÓN pública relativa a la aprobación inicial del proyecto de urbanización del sect...
  Razonamiento: El texto menciona explícitamente "aprobación inicial del proyecto de urbanización" (dispara PROY_URB y fase_inicial) y l

ID 13 | GT=['PGOU'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PLAN_ESP']
  Acuerdo de 25 de noviembre de 2024, del Ayuntamiento de Almedinilla, por el que se aprueba...
  Razonamiento: El texto menciona "aprobación definitiva del documento de revisión parcial del Plan General de Ordenación Urbanística",

ID 14 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Gerencia Municipal de Urbanismo.- Anuncio de 29 de enero de 2025, por el que se somete a i...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación" (PGOU) y "Modificación Menor" (MOD_PUN). La frase "somete

ID 15 | GT=['PROY_URB'] | PRED=['PGOU']
  Falta: ['PROY_URB'] | Sobra: ['PGOU']
  ACUERDO de 18 de febrero de 2025, del Pleno del Ayuntamiento de Saldaña de Burgos (Burgos)...
  Razonamiento: El texto menciona "Normas Urbanísticas Municipales" que encaja con PGOU, y se trata de una "aprobación definitiva", adem

ID 16 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO por el que se somete a información pública la modificación puntual número 2 del Pl...
  Razonamiento: "La descripción menciona explícitamente 'anuncio', 'información pública' (fase_ip), 'modificación puntual número 2' (MOD

ID 17 | GT=['MOD_PUN'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: ['MOD_PUN'] | Sobra: ['PGOU', 'PLAN_ESP']
  Plan general de urbanismo – Acuerdo de 12 de febrero de 2025, del Consejo de Gobierno, por...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación Urbana" (etiqueta PGOU) y "Área de Planeamiento Específico

ID 18 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ACUERDO de 27 de febrero de 2025, de la Comisión Territorial de Medio Ambiente y Urbanismo...
  Razonamiento: El texto menciona explícitamente "modificación n.º 2 de las Normas Urbanísticas Municipales", lo que activa la categoría

ID 19 | GT=['MOD_PUN'] | PRED=['DIC_INT', 'MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['DIC_INT', 'PGOU']
  Normas urbanísticas – Orden 878/2025, de 7 de marzo, de la Consejería de Medio Ambiente, A...
  Razonamiento: El texto indica "Modificación Puntual" (MOD_PUN) de las "Normas Subsidiarias" (PGOU), la aprobación "definitivamente", y

ID 20 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  INFORMACIÓN pública relativa a la aprobación inicial de la modificación n.º 5 del Plan Gen...
  Razonamiento: El texto menciona explícitamente "información pública relativa a la aprobación inicial de la modificación n.º 5 del Plan

ID 21 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 30/01/2025, del Ayuntamiento de Ciudad Real, sobre información pública de la al...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación Urbana" (PGOU) y "Unidad de Ejecución", así como "Proyecto

ID 22 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Acuerdo de aprobación definitiva con prescripciones relativa a la Modificación puntual nº....
  Razonamiento: El texto menciona explícitamente "Normas Subsidiarias de planeamiento", que corresponde a la categoría PGOU (equivalente

ID 23 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO por el que se somete a información pública la modificación puntual número 10 del P...
  Razonamiento: La descripción menciona explícitamente "Plan general de ordenación urbana" (etiqueta PGOU) y "modificación puntual númer

ID 30 | GT=['PLAN_ESP'] | PRED=['PLAN_ESP', 'PROY_URB']
  Falta: [] | Sobra: ['PROY_URB']
  ACUERDO de 20 de diciembre de 2024, del Pleno del Ayuntamiento de Burgos, relativo a la ap...
  Razonamiento: El texto menciona explícitamente un "Estudio de detalle" (categoría PLAN_ESP) y su localización en un "polígono industri

ID 35 | GT=['PLAN_ESP'] | PRED=['MOD_PUN', 'PLAN_ESP']
  Falta: [] | Sobra: ['MOD_PUN']
  INFORMACIÓN pública relativa a la aprobación inicial del estudio de detalle para la modifi...
  Razonamiento: El texto menciona explícitamente "estudio de detalle" (PLAN_ESP) y "modificación de la alteración existente" (MOD_PUN).

ID 36 | GT=['PLAN_ESP'] | PRED=['PLAN_ESP', 'PROY_URB']
  Falta: [] | Sobra: ['PROY_URB']
  Aprobación inicial de Estudio de Detalle en la parcela 218 del polígono 4...
  Razonamiento: El texto contiene explícitamente la palabra "aprobación inicial", lo cual indica que el acto es una aprobación inicial (

ID 43 | GT=['PLAN_ESP'] | PRED=['PLAN_ESP', 'PROY_URB']
  Falta: [] | Sobra: ['PROY_URB']
  Aprobación inicial de Estudio de Detalle en la parcela  522 del polígono 1...
  Razonamiento: La descripción menciona explícitamente "Aprobación inicial" de un "Estudio de Detalle", lo que corresponde a la categorí

ID 45 | GT=['PROY_URB'] | PRED=['PLAN_ESP', 'PROY_URB']
  Falta: [] | Sobra: ['PLAN_ESP']
  Anuncio de aprobación provisional de cuenta de liquidación definitiva del proyecto de urba...
  Razonamiento: El texto menciona explícitamente "Plan Parcial" (etiqueta PLAN_ESP) y "proyecto de urbanización" (etiqueta PROY_URB), ad

ID 46 | GT=['PLAN_ESP'] | PRED=['LIC_URB', 'PLAN_ESP']
  Falta: [] | Sobra: ['LIC_URB']
  Sometimiento a información pública de la documentación integrante del Avance del Plan Espe...
  Razonamiento: El texto menciona explícitamente "Sometimiento a información pública" (actividad de fase IP) y "Plan Especial de Reorden

ID 48 | GT=['PLAN_ESP'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PGOU']
  Aprobación inicial de Estudio de Detalle en las unidades UC-2.3 y UC-2.6 de suelo urbano c...
  Razonamiento: La descripción menciona "Estudio de Detalle", que corresponde a la categoría PLAN_ESP, y se trata en el contexto del PGO

ID 50 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ACUERDO de 19 de diciembre de 2024, del Pleno del Ayuntamiento de Palencia, por el que se ...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación Urbana" (PGOU) y "modificación puntual", así como "aprobaci

ID 51 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Informe Ambiental Estratégico de la Modificación Puntual 1/2022 de las Normas Subsidiarias...
  Razonamiento: El texto menciona explícitamente "Informe Ambiental Estratégico de la Modificación Puntual 1/2022 de las Normas Subsidia

ID 52 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 14/01/2025, del Ayuntamiento de Ciudad Real, sobre información pública de la Mo...
  Razonamiento: La descripción contiene explícitamente "Modificación Puntual número 4" (MOD_PUN) y menciona que modifica el "Plan Genera

ID 53 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Aprobación inicial del proyecto de modificación puntual de las Normas Subsidiarias en la c...
  Razonamiento: El texto menciona explícitamente "Aprobación inicial" (fase_inicial) y "modificación puntual de las Normas Subsidiarias"

ID 54 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO por el que se somete a información pública la modificación puntual número 4 del Pl...
  Razonamiento: El texto contiene explícitamente "anuncio", "modificación puntual número 4" (MOD_PUN) y "Plan general de ordenación urba

ID 55 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Aprobación inicial de la Modificación Puntual Número 15 del Plan General Municipal de Cala...
  Razonamiento: El texto menciona explícitamente "Aprobación inicial" (subcategoría fase_inicial) y "Modificación Puntual Número 15 del

ID 56 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ACUERDO de 26 de febrero de 2025, de la Comisión Territorial de Medio Ambiente y Urbanismo...
  Razonamiento: El texto menciona explícitamente "acuerdo" (tipo de acto), "aprobación definitiva" (subcategoría fase_definitiva), "modi

ID 57 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ACUERDO de 26 de febrero de 2025, de la Comisión Territorial de Medio Ambiente y Urbanismo...
  Razonamiento: El texto menciona "Normas Urbanísticas Municipales" (PGOU) y "modificación puntual número 56", además de "aprobación def

ID 58 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 24 de marzo de 2025 sobre exposición al público de aprobación de viabilidad e i...
  Razonamiento: El texto menciona explícitamente "Plan General Urbano" (etiqueta PGOU) y "inicial modificación puntual" (etiqueta MOD_PU

ID 60 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ORDEN MAV/129/2025, de 12 de febrero, por la que se formula el informe ambiental estratégi...
  Razonamiento: El texto menciona "Plan General de Ordenación Urbana" (etiqueta PGOU) y "modificación puntual" (etiqueta MOD_PUN). El fr

ID 61 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 27/01/2025, del Ayuntamiento de Esquivias (Toledo), sobre información pública d...
  Razonamiento: El texto menciona explícitamente "Modificación Puntual número 5 de las Normas Subsidiarias", lo que indica tanto la cate

ID 62 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 24 de enero de 2025 sobre aprobación inicial de la modificación puntual 2/2024/...
  Razonamiento: El texto menciona explícitamente "modificación puntual 2/2024/OD" que activa la etiqueta MOD_PUN y se refiere a una "apr

ID 63 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ORDEN MAV/55/2025, de 24 de enero, por la que se formula el informe ambiental estratégico ...
  Razonamiento: El texto menciona "modificación puntual" y "Normas Urbanísticas Municipales", disparando las categorías MOD_PUN y PGOU r

ID 64 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ORDEN MAV/91/2025, de 4 de febrero, por la que se formula el informe ambiental estratégico...
  Razonamiento: "La publicación menciona explícitamente 'modificación puntual de las Normas Urbanísticas Municipales', que corresponde a

ID 65 | GT=['MOD_PUN'] | PRED=['LIC_URB', 'MOD_PUN']
  Falta: [] | Sobra: ['LIC_URB']
  ORDEN MAV/108/2025, de 7 de febrero, por la que se formula la declaración ambiental estrat...
  Razonamiento: El texto menciona explícitamente "modificación puntual n.º 2/2021 de las Normas Urbanísticas Municipales", justificando

ID 68 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Edicto de 29 de enero de 2025, de la Gerencia Municipal de Urbanismo del Excmo. Ayuntamien...
  Razonamiento: El texto menciona explícitamente "PGOU de Almería" (etiqueta PGOU) y "78.ª modificación puntual" (etiqueta MOD_PUN). El

ID 69 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 28 de enero de 2025 sobre aprobación de la modificación puntual n.º 2 a-b-c-e d...
  Razonamiento: El texto menciona explícitamente "modificación puntual" (categoría MOD_PUN) y "Plan General Municipal" (categoría PGOU).

ID 70 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  INFORMACIÓN pública relativa a la aprobación inicial de la modificación puntual n.º 4 de l...
  Razonamiento: El texto menciona explícitamente "Normas Urbanísticas Municipales" (equivalente a PGOU), "modificación puntual" (MOD_PUN

ID 71 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PGOU', 'PLAN_ESP']
  ANUNCIO de la aprobación definitiva de la modificación puntual del Plan general de ordenac...
  Razonamiento: El texto menciona explícitamente "anuncio de la aprobación definitiva" (dispara fase_definitiva y act_type), "modificaci

ID 72 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO de la modificación puntual del Plan general de ordenación urbana 82 en la avenida ...
  Razonamiento: El texto menciona explícitamente "modificación puntual del Plan general de ordenación urbana 82", lo cual justifica las

ID 73 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PLAN_ESP']
  Falta: [] | Sobra: ['PLAN_ESP']
  Aprobación inicial de la modificación puntual n.º 8 del Plan Especial de Ordenación y Prot...
  Razonamiento: La descripción contiene explícitamente "modificación puntual n.º 8" (MOD_PUN), "Plan Especial de Ordenación..." (PLAN_ES

ID 74 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Acuerdo de 30 de noviembre de 2023, de la Comisión de Urbanismo y Ordenación del Territori...
  Razonamiento: El texto menciona explícitamente "aprobación definitiva" de la "modificación puntual n.º 1 del Plan General Municipal",

ID 77 | GT=['PROY_URB'] | PRED=[]
  Falta: ['PROY_URB'] | Sobra: []
  Anuncio de 14 de marzo de 2025, de la Dirección General de Ordenación del Territorio, Urba...
  Razonamiento: El texto menciona "parcelación urbanística" pero el acto es una notificación de un procedimiento sancionador por la adqu

ID 79 | GT=['PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: ['LIC_URB']
  Anuncio de 20 de diciembre de 2024, de la Dirección General de Ordenación del Territorio, ...
  Razonamiento: El anuncio requiere el cumplimiento de una resolución sobre parcelación urbanística en San Roque, lo que se relaciona co

ID 79 | GT=['PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: ['LIC_URB']
  Anuncio de 20 de diciembre de 2024, de la Dirección General de Ordenación del Territorio, ...
  Razonamiento: El texto menciona "cumplimiento de la resolución finalizadora" y "parcelación urbanística", lo que activa la categoría L

ID 82 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PGOU', 'PLAN_ESP']
  ANUNCIO de la modificación puntual del Plan parcial de la unidad de ejecución número 1 del...
  Razonamiento: El texto menciona explícitamente "Plan parcial" (PLAN_ESP), "unidad de ejecución" (PROY_URB, pero no es el foco principa

ID 83 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO en relación a la información pública de la aprobación inicial del proyecto de repa...
  Razonamiento: El texto menciona explícitamente "unidad de ejecución del plan de reforma interior UE 4.2. Montesano", lo que correspond

ID 84 | GT=['PROY_URB'] | PRED=[]
  Falta: ['PROY_URB'] | Sobra: []
  Anuncio de 30 de enero de 2025, de la Dirección General de Ordenación del Territorio, Urba...
  Razonamiento: La publicación es un anuncio de inicio de procedimiento sancionador por "adquisición de cuotas y porcentajes de propieda

ID 86 | GT=['PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: ['LIC_URB']
  Anuncio de 20 de diciembre de 2024, de la Dirección General de Ordenación del Territorio, ...
  Razonamiento: El anuncio requiere el cumplimiento de una resolución sobre parcelación urbanística en San Roque, lo que se relaciona co

ID 86 | GT=['PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: ['LIC_URB']
  Anuncio de 20 de diciembre de 2024, de la Dirección General de Ordenación del Territorio, ...
  Razonamiento: El texto menciona "cumplimiento de la resolución finalizadora" y "parcelación urbanística", lo que activa la categoría L

ID 88 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']

---

##  7. Experimento 2 - Prompt v2 (variantes regionales)

**Problema**: (rellenar tras el análisis de errores del §6)

**Objetivo**: Verificar si añadir la tabla de equivalencias regionales (POUM=PGOU, POM=PGOU, etc.) y la regla EMOT navarro mejora el F1 de PGOU.

**Enfoque**: Qwen 3.5 9B · SYSTEM_PROMPT_B2_V2 · zero-shot · sin contexto N1.

**Resultados**: pendiente.

In [19]:
agent_b2_v2 = build_agent(
    model, "v2",
    output_type=ClassifierOutputB2,
    prompt_registry=PROMPT_REGISTRY_B2,
)

df_b2_exp2 = await run_experiment(
    agent_b2_v2, df_anotado_run,
    use_n1_context=False, concurrency=1,
    output_path="../results/b2_exp2_promptv2_qwen9b.csv",
    desc="B2 Exp2 - Prompt v2",
)
df_b2_exp2.head(3)

  Reanudando: 149/150 registros ya clasificados

,id,bulletin,description,grupo_muestreo,is_relevant_gt,categories_gt,subcategories_gt,notas_anotador,is_relevant_pred,act_type_pred,categories_pred,subcategories_pred,confidence,reasoning,duration_s
0,0,boja,"Resolución de 16 de enero de 2025, de la Deleg...",PGOU,True,MOD_PUN,fase_definitiva,Publicacion registro Modificacion PGOU Mijas,True,resolución,"[""PGOU"", ""MOD_PUN""]",[],0.98,"La descripción menciona explícitamente ""Modifi...",179.477
1,1,bocm,Plan general de urbanismo\n– Acuerdo de 12 de ...,PGOU,True,MOD_PUN,fase_definitiva,Decimoctava Modificacion Puntual PGOU Getafe,True,acuerdo,"[""PGOU"", ""MOD_PUN""]","[""fase_definitiva""]",0.98,"El texto menciona explícitamente ""Plan General...",64.860
2,2,docm,"Anuncio de 28/01/2025, del Ayuntamiento de Vil...",PGOU,True,PLAN_ESP,fase_ip,PERIM exposicion publica - Plan Especial Refor...,True,anuncio,"[""PGOU"", ""PLAN_ESP""]","[""fase_ip"", ""uso_energetico"", ""uso_rustico""]",0.98,"El texto menciona ""Plan Especial de Reforma In...",137.210

In [20]:
df_b2_exp2 = pd.read_csv("../results/b2_exp2_promptv2_qwen9b.csv")
df_eval_b2_2 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b2_exp2[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b2_2 = compute_metrics_B2(df_eval_b2_2, "Experimento B2-2 - Prompt v2")
print_errors_B2(df_eval_b2_2, m_b2_2["exact"], m_b2_2["rel"], label="B2 Experimento 2 - Prompt v2")

-- Experimento B2-2 - Prompt v2 --

is_relevant  Acc=0.908  P=0.908  R=1.000  F1=0.952
             TP=138  FP=14  FN=0  TN=0

N2 multilabel:
  Micro F1:      0.767
  Macro F1:      0.595
  Hamming Loss:  0.0735
  Jaccard:       0.630
  Subset Acc:    0.638

  Label             P      R     F1   Sup
  -------------------------------------
  PGOU          0.069  0.667  0.125     3
  PLAN_ESP      0.889  0.960  0.923    25
  MOD_PUN       1.000  0.841  0.914    44
  PROY_URB      0.895  0.739  0.810    23
  LIC_URB       0.857  0.750  0.800    40
  DIC_INT       0.000  0.000  0.000     5
  -------------------------------------
  Macro                       0.595

  Subset Acc por cardinalidad:
    card=0 (no relevante) : 1.000  (14/14)
    card=1 (1) : 0.603  (82/136)
    card=2 (2) : 0.500  (1/2)

  Confianza: media=0.948  min=0.000  max=1.000

-- Errores N2 en relevantes · B2 Experimento 2 - Prompt v2 --
Total: 55

ID 0 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Resolución de 16 de enero de 2025, de la Delegación Territorial de Fomento, Articulación d...
  Razonamiento: La descripción menciona explícitamente "Modificación del Plan General de Ordenación Urbana (PGOU) de Mijas" (señalando P

ID 1 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Plan general de urbanismo – Acuerdo de 12 de marzo de 2025, del Consejo de Gobierno, por e...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación Urbana" (etiqueta PGOU) y "Decimoctava Modificación Puntual

ID 2 | GT=['PLAN_ESP'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 28/01/2025, del Ayuntamiento de Villar de Olalla (Cuenca), sobre exposición púb...
  Razonamiento: El texto menciona "Plan Especial de Reforma Interior" y "Normas Subsidiarias", lo que activa las categorías PLAN_ESP y P

ID 3 | GT=['PROY_URB'] | PRED=['PGOU']
  Falta: ['PROY_URB'] | Sobra: ['PGOU']
  Anuncio de 27/12/2024, del Ayuntamiento de Albacete, de la Gerencia Municipal de Urbanismo...
  Razonamiento: El texto menciona "Plan General de Ordenación Urbana" (etiqueta PGOU) y "información pública" sobre una plica presentada

ID 4 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Viceconsejería de Planificación Territorial y Reto Demográfico.- Anuncio por el que se hac...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación" (PGOU) y "Modificación Menor" (MOD_PUN). El anuncio hace p

ID 5 | GT=['PROY_URB'] | PRED=['PGOU']
  Falta: ['PROY_URB'] | Sobra: ['PGOU']
  Anuncio de 20 de febrero de 2025 sobre aprobación inicial del Programa de Ejecución de la ...
  Razonamiento: La publicación es un anuncio de "aprobación inicial" (disparador de fase_inicial) del "Programa de Ejecución... de las N

ID 6 | GT=['MOD_PUN'] | PRED=['LIC_URB', 'MOD_PUN', 'PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['LIC_URB', 'PGOU', 'PROY_URB']
  Anuncio sobre aprobación inicial de la modificación puntual del Plan general de ordenación...
  Razonamiento: El texto menciona explícitamente "Plan general de ordenación municipal" (etiqueta PGOU) y una "modificación puntual del

ID 7 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  EDICTO de aprobación del informe ambiental y territorial estratégico, por el procedimiento...
  Razonamiento: El texto menciona explícitamente "modificación puntual" de la ordenación del "Plan general de ordenación urbana", activa

ID 8 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Informe Ambiental Estratégico de la Modificación Puntual número 1, del Plan General de Ord...
  Razonamiento: El texto identifica claramente una "Modificación Puntual" del "Plan General de Ordenación Urbana", lo cual activa las ca

ID 9 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO de 6 de noviembre de 2024, por el que se somete a información pública la aprobació...
  Razonamiento: El texto menciona "Aprobación inicial" (dispara fase_inicial) y "somete a información pública" (dispara fase_ip). La "Mo

ID 10 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO del Acuerdo de 25 de noviembre de 2024, de la Junta de Gobierno Local, del informe...
  Razonamiento: El texto menciona explícitamente "modificación puntual del Plan general de ordenación urbana" (MOD_PUN) sobre el PGOU, y

ID 11 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']
  INFORMACIÓN pública relativa a la aprobación inicial del proyecto de urbanización del sect...
  Razonamiento: El texto cita explícitamente el "Plan General de Ordenación Urbana" (PGOU) y un "proyecto de urbanización", con una fase

ID 14 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Gerencia Municipal de Urbanismo.- Anuncio de 29 de enero de 2025, por el que se somete a i...
  Razonamiento: El texto menciona "Plan General de Ordenación" (PGOU) y "Modificación Menor" (MOD_PUN). Indica también "aprobación inici

ID 15 | GT=['PROY_URB'] | PRED=['LIC_URB', 'PROY_URB']
  Falta: [] | Sobra: ['LIC_URB']
  ACUERDO de 18 de febrero de 2025, del Pleno del Ayuntamiento de Saldaña de Burgos (Burgos)...
  Razonamiento: El texto menciona "aprobado definitivamente" lo que indica fase_definitiva, y "proyecto de actuación" junto con "unidad

ID 16 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO por el que se somete a información pública la modificación puntual número 2 del Pl...
  Razonamiento: "ANUNCIO por el que se somete a información pública la modificación puntual número 2 del Plan general de ordenación urba

ID 17 | GT=['MOD_PUN'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: ['MOD_PUN'] | Sobra: ['PGOU', 'PLAN_ESP']
  Plan general de urbanismo – Acuerdo de 12 de febrero de 2025, del Consejo de Gobierno, por...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación Urbana" (etiqueta PGOU) y la creación de un "Área de Planea

ID 18 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ACUERDO de 27 de febrero de 2025, de la Comisión Territorial de Medio Ambiente y Urbanismo...
  Razonamiento: El texto menciona "acuerdo" como acto administrativo (act_type), "aprobación definitiva" indicando fase_definitiva, y la

ID 19 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Normas urbanísticas – Orden 878/2025, de 7 de marzo, de la Consejería de Medio Ambiente, A...
  Razonamiento: El texto menciona explícitamente "Modificación Puntual de las Normas Subsidiarias", lo que activa las categorías MOD_PUN

ID 20 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  INFORMACIÓN pública relativa a la aprobación inicial de la modificación n.º 5 del Plan Gen...
  Razonamiento: La descripción menciona explícitamente "modificación n.º 5 del Plan General de Ordenación Urbana" (etiqueta MOD_PUN y PG

ID 21 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 30/01/2025, del Ayuntamiento de Ciudad Real, sobre información pública de la al...
  Razonamiento: Se trata de un anuncio de información pública (fase_ip) sobre una alternativa técnica para una Unidad de Ejecución del P

ID 22 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Acuerdo de aprobación definitiva con prescripciones relativa a la Modificación puntual nº....
  Razonamiento: El texto menciona explícitamente "Normas Subsidiarias de planeamiento" lo que corresponde a la categoría PGOU. Además, s

ID 23 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO por el que se somete a información pública la modificación puntual número 10 del P...
  Razonamiento: El texto menciona explícitamente "modificación puntual" (MOD_PUN), "Plan general de ordenación urbana" (PGOU) y "informa

ID 24 | GT=['MOD_PUN'] | PRED=['PGOU']
  Falta: ['MOD_PUN'] | Sobra: ['PGOU']
  Modificación puntual de las normas subsidiarias de Consell para la delimitación y ordenaci...
  Razonamiento: La descripción menciona "Modificación puntual de las normas subsidiarias", que es la frase exacta para la etiqueta MOD_P

ID 33 | GT=['PLAN_ESP'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 29 de enero de 2025 sobre aprobación inicial del Estudio de Detalle de la parce...
  Razonamiento: El texto menciona "aprobación inicial del Estudio de Detalle", lo que corresponde a la categoría PLAN_ESP según las seña

ID 42 | GT=['PLAN_ESP'] | PRED=[]
  Falta: ['PLAN_ESP'] | Sobra: []
  RESOLUCIÓN de 28 de enero de 2025, del Director de Administración Ambiental, por la que se...
  Razonamiento: La publicación es un informe ambiental estratégico, no un acto de gestión urbanística directa (no hay "plan especial", "

ID 44 | GT=['PLAN_ESP'] | PRED=['PLAN_ESP', 'PROY_URB']
  Falta: [] | Sobra: ['PROY_URB']
  Aprobación inicial de Estudio de Detalle en las parcelas 570 y 571 del área de reparto AR2...
  Razonamiento: El texto menciona "Aprobación inicial de Estudio de Detalle" lo que corresponde a la subcategoría fase_inicial y las cat

ID 45 | GT=['PROY_URB'] | PRED=['PLAN_ESP']
  Falta: ['PROY_URB'] | Sobra: ['PLAN_ESP']
  Anuncio de aprobación provisional de cuenta de liquidación definitiva del proyecto de urba...
  Razonamiento: El texto menciona "Plan Parcial" que encaja con PLAN_ESP y "aprobación provisional" que indica la subcategoría fase_prov

ID 51 | GT=['MOD_PUN'] | PRED=[]
  Falta: ['MOD_PUN'] | Sobra: []
  Informe Ambiental Estratégico de la Modificación Puntual 1/2022 de las Normas Subsidiarias...
  Razonamiento: El documento es un "Informe Ambiental Estratégico" de una "Modificación Puntual 1/2022". Según las reglas críticas, MOD_

ID 53 | GT=['MOD_PUN'] | PRED=[]
  Falta: ['MOD_PUN'] | Sobra: []
  Aprobación inicial del proyecto de modificación puntual de las Normas Subsidiarias en la c...
  Razonamiento: El texto se refiere a "modificación puntual de las Normas Subsidiarias", que según la regla 1 debe clasificarse como MOD

ID 58 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 24 de marzo de 2025 sobre exposición al público de aprobación de viabilidad e i...
  Razonamiento: El texto menciona "exposición al público de... inicial modificación puntual del Plan General Urbano" (actividad de fase_

ID 60 | GT=['MOD_PUN'] | PRED=[]
  Falta: ['MOD_PUN'] | Sobra: []
  ORDEN MAV/129/2025, de 12 de febrero, por la que se formula el informe ambiental estratégi...
  Razonamiento: El texto menciona "informe ambiental estratégico de la modificación puntual n.º 9 del Plan General", lo que indica que e

ID 62 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Anuncio de 24 de enero de 2025 sobre aprobación inicial de la modificación puntual 2/2024/...
  Razonamiento: El texto menciona explícitamente "modificación puntual" y "aprobación inicial", indicando una modificación del plan gene

ID 68 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Edicto de 29 de enero de 2025, de la Gerencia Municipal de Urbanismo del Excmo. Ayuntamien...
  Razonamiento: El texto describe un procedimiento de Evaluación Ambiental Estratégica del PGOU, pero el objeto central es la "78.ª modi

ID 73 | GT=['MOD_PUN'] | PRED=[]
  Falta: ['MOD_PUN'] | Sobra: []
  Aprobación inicial de la modificación puntual n.º 8 del Plan Especial de Ordenación y Prot...
  Razonamiento: La publicación se refiere a "modificación puntual" de un plan especial, lo cual indica un acto jurídico de modificación

ID 75 | GT=['LIC_URB', 'PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: []
  INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rú...
  Razonamiento: "autorización de uso excepcional de suelo rústico" → LIC_URB (suelo rústico). "Información pública relativa a la solicit

ID 81 | GT=['PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: ['LIC_URB']
  APROBACIÓN definitiva del Convenio Urbanístico de obtención de terrenos para su destino de...
  Razonamiento: "APROBACIÓN definitiva" indica una acción de legitimación final (etapa fase_definitiva). El texto menciona "destino de d

ID 82 | GT=['MOD_PUN'] | PRED=['PLAN_ESP']
  Falta: ['MOD_PUN'] | Sobra: ['PLAN_ESP']
  ANUNCIO de la modificación puntual del Plan parcial de la unidad de ejecución número 1 del...
  Razonamiento: La descripción menciona explícitamente "modificación puntual del Plan parcial", lo que corresponde a la categoría PLAN_E

ID 83 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO en relación a la información pública de la aprobación inicial del proyecto de repa...
  Razonamiento: El texto menciona "unidad de ejecución del plan de reforma interior" que implica la aprobación inicial (fase_inicial) y

ID 85 | GT=['PROY_URB'] | PRED=[]
  Falta: ['PROY_URB'] | Sobra: []
  Denominación de la vía pública y numeración de las parcelas resultantes del proyecto de re...
  Razonamiento: nan

ID 91 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio por el que se somete a información pública la solicitud de autorización administra...
  Razonamiento: El documento es un anuncio de información pública sobre una autorización de actuación específica de interés público en s

ID 94 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio complementario del Departament d'Acció Climàtica, Alimentació i Agenda Rural - Ser...
  Razonamiento: La publicación pertenece a la Generalitat de Catalunya (Servicios Territoriales), no al BOE estatal, y trata sobre una a

ID 95 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rú...
  Razonamiento: nan

ID 105 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rú...
  Razonamiento: nan

ID 108 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rú...
  Razonamiento: nan

ID 120 | GT=['DIC_INT'] | PRED=['LIC_URB']
  Falta: ['DIC_INT'] | Sobra: ['LIC_URB']
  ANUNCIO por el que se somete a información pública la declaración de interés comunitario p...
  Razonamiento: El texto menciona "declaración de interés comunitario" para una "atribución de uso y aprovechamiento en suelo no urbaniz

ID 121 | GT=['DIC_INT'] | PRED=[]
  Falta: ['DIC_INT'] | Sobra: []
  ANUNCIO de la solicitud de declaración de interés comunitario de regularización de activid...
  Razonamiento: La descripción menciona "declaración de interés comunitario" y "suelo no urbanizable", pero según la regla 4, DIC_INT es

ID 122 | GT=['DIC_INT'] | PRED=[]
  Falta: ['DIC_INT'] | Sobra: []
  ANUNCI de la declaración de interés comunitario para una atribución de uso y aprovechamien...
  Razonamiento: El texto menciona "declaración de interés comunitario" (DIQUE), pero según la regla 4, esta etiqueta DIC_INT es exclusiv

ID 123 | GT=['DIC_INT'] | PRED=[]
  Falta: ['DIC_INT'] | Sobra: []
  ANUNCIO de la solicitud de ampliación de declaración de interés comunitario de una activid...
  Razonamiento: El texto se refiere a una "declaración de interés comunitario" de un camping, pero al amparo del TRLOTUP (texto refundid

ID 124 | GT=['DIC_INT'] | PRED=['LIC_URB']
  Falta: ['DIC_INT'] | Sobra: ['LIC_URB']
  ANUNCIO por el cual se somete a información pública la declaración de interés comunitario ...
  Razonamiento: El texto menciona "declaración de interés comunitario" en un acto del DOGV (Comunitat Valenciana), lo que cumple con el

ID 125 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  CORRECCIÓN de errores del anuncio de información pública relativa a la solicitud de autori...
  Razonamiento: nan

ID 128 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio de los Servicios Territoriales del Departamento de Territorio, Vivienda y Transici...
  Razonamiento: El texto hace referencia a una "declaración de utilidad pública" para un proyecto solar fotovoltaico, que es un trámite

ID 131 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio complementario por el que se somete a información pública la solicitud de autoriza...
  Razonamiento: El texto describe una solicitud de "autorización administrativa previa" y "declaración de utilidad pública" para un parq

ID 132 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Resolución TER/4753/2024, de 17 de diciembre, por la que se otorga a Energía Inagotable de...
  Razonamiento: La publicación es una resolución que otorga autorización administrativa y construcción de una planta solar fotovoltaica

ID 134 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Resolución TER/395/2025, de 10 de febrero, de corrección de errores materiales en la Resol...
  Razonamiento: Es un acto de corrección de errores (act_type: "corrección_errores") sobre una resolución de autorización administrativa

ID 140 | GT=['PGOU'] | PRED=[]
  Falta: ['PGOU'] | Sobra: []
  Exposición pública Avance/Borrador del Plan General y el Plan de Ordenación Detallada de S...
  Razonamiento: nan

---

##  8. Experimento 3 - Prompt v3 (reglas de frontera)

**Problema**: (rellenar tras el análisis de errores del §7)

**Objetivo**: Verificar si las reglas de frontera (MOD_PUN≠PGOU, DIC_INT≠DUP, LIC_URB con renovables, PLAN_ESP≠PGOU) reducen los errores de clasificacion.

**Enfoque**: Qwen 3.5 9B · SYSTEM_PROMPT_B2_V3 · zero-shot · sin contexto N1.

**Resultados**: pendiente.

In [21]:
agent_b2_v3 = build_agent(
    model, "v3",
    output_type=ClassifierOutputB2,
    prompt_registry=PROMPT_REGISTRY_B2,
)

df_b2_exp3 = await run_experiment(
    agent_b2_v3, df_anotado_run,
    use_n1_context=False, concurrency=1,
    output_path="../results/b2_exp3_promptv3_qwen9b.csv",
    desc="B2 Exp3 - Prompt v3",
)
df_b2_exp3.head(3)

  Reanudando: 149/150 registros ya clasificados

,id,bulletin,description,grupo_muestreo,is_relevant_gt,categories_gt,subcategories_gt,notas_anotador,is_relevant_pred,act_type_pred,categories_pred,subcategories_pred,confidence,reasoning,duration_s
0,0,boja,"Resolución de 16 de enero de 2025, de la Deleg...",PGOU,True,MOD_PUN,fase_definitiva,Publicacion registro Modificacion PGOU Mijas,True,resolución,"[""MOD_PUN""]",[],0.98,"La publicación es una ""Modificación del Plan G...",121.850
1,1,bocm,Plan general de urbanismo\n– Acuerdo de 12 de ...,PGOU,True,MOD_PUN,fase_definitiva,Decimoctava Modificacion Puntual PGOU Getafe,True,acuerdo,"[""MOD_PUN""]","[""fase_definitiva""]",0.98,"El texto menciona explícitamente ""Decimoctava ...",52.278
2,2,docm,"Anuncio de 28/01/2025, del Ayuntamiento de Vil...",PGOU,True,PLAN_ESP,fase_ip,PERIM exposicion publica - Plan Especial Refor...,True,anuncio,"[""PGOU""]","[""fase_ip"", ""uso_equipamiento"", ""uso_rustico""]",0.85,"""exposición pública del Plan Especial de Refor...",59.080

In [22]:
df_b2_exp3 = pd.read_csv("../results/b2_exp3_promptv3_qwen9b.csv")
df_eval_b2_3 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b2_exp3[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b2_3 = compute_metrics_B2(df_eval_b2_3, "Experimento B2-3 - Prompt v3")
print_errors_B2(df_eval_b2_3, m_b2_3["exact"], m_b2_3["rel"], label="B2 Experimento 3 - Prompt v3")

-- Experimento B2-3 - Prompt v3 --

is_relevant  Acc=0.908  P=0.908  R=1.000  F1=0.952
             TP=138  FP=14  FN=0  TN=0

N2 multilabel:
  Micro F1:      0.881
  Macro F1:      0.845
  Hamming Loss:  0.0351
  Jaccard:       0.760
  Subset Acc:    0.822

  Label             P      R     F1   Sup
  -------------------------------------
  PGOU          0.375  1.000  0.545     3
  PLAN_ESP      0.808  0.840  0.824    25
  MOD_PUN       1.000  0.955  0.977    44
  PROY_URB      1.000  0.783  0.878    23
  LIC_URB       0.968  0.750  0.845    40
  DIC_INT       1.000  1.000  1.000     5
  -------------------------------------
  Macro                       0.845

  Subset Acc por cardinalidad:
    card=0 (no relevante) : 0.929  (13/14)
    card=1 (1) : 0.824  (112/136)
    card=2 (2) : 0.000  (0/2)

  Confianza: media=0.950  min=0.600  max=1.000

-- Errores N2 en relevantes · B2 Experimento 3 - Prompt v3 --
Total: 26

ID 2 | GT=['PLAN_ESP'] | PRED=['PGOU']
  Falta: ['PLAN_ESP'] | Sobra: ['PGOU']
  Anuncio de 28/01/2025, del Ayuntamiento de Villar de Olalla (Cuenca), sobre exposición púb...
  Razonamiento: "exposición pública del Plan Especial de Reforma Interior de Mejora (Perim)" indica fase_ip y, dado que es un PERIM, se

ID 3 | GT=['PROY_URB'] | PRED=['PGOU']
  Falta: ['PROY_URB'] | Sobra: ['PGOU']
  Anuncio de 27/12/2024, del Ayuntamiento de Albacete, de la Gerencia Municipal de Urbanismo...
  Razonamiento: La publicación menciona el "Plan General de Ordenación Urbana de Albacete", lo que indica un acto relacionado con la nor

ID 5 | GT=['PROY_URB'] | PRED=[]
  Falta: ['PROY_URB'] | Sobra: []
  Anuncio de 20 de febrero de 2025 sobre aprobación inicial del Programa de Ejecución de la ...
  Razonamiento: Texto: "Programa de Ejecución de la UE3" es un instrumento energético (Energía Sostenible y Planificación Estratégica),

ID 17 | GT=['MOD_PUN'] | PRED=['PLAN_ESP']
  Falta: ['MOD_PUN'] | Sobra: ['PLAN_ESP']
  Plan general de urbanismo – Acuerdo de 12 de febrero de 2025, del Consejo de Gobierno, por...
  Razonamiento: El texto menciona "Área de Planeamiento Específico 10.24", lo que en la práctica es equivalente a un Plan Especial, por

ID 21 | GT=['PROY_URB'] | PRED=['PGOU']
  Falta: ['PROY_URB'] | Sobra: ['PGOU']
  Anuncio de 30/01/2025, del Ayuntamiento de Ciudad Real, sobre información pública de la al...
  Razonamiento: El texto menciona explícitamente "Plan General de Ordenación Urbana" y su "alternativa técnica", indicando un acto sobre

ID 31 | GT=['PLAN_ESP', 'PROY_URB'] | PRED=[]
  Falta: ['PLAN_ESP', 'PROY_URB'] | Sobra: []
  Aprobación inicial del Programa de Actuación, del cambio de sistema de gestión y de los es...
  Razonamiento: El texto describe la "Aprobación inicial del Programa de Actuación" y cambios estatutarios, lo cual corresponde a gestió

ID 35 | GT=['PLAN_ESP'] | PRED=[]
  Falta: ['PLAN_ESP'] | Sobra: []
  INFORMACIÓN pública relativa a la aprobación inicial del estudio de detalle para la modifi...
  Razonamiento: nan

ID 42 | GT=['PLAN_ESP'] | PRED=[]
  Falta: ['PLAN_ESP'] | Sobra: []
  RESOLUCIÓN de 28 de enero de 2025, del Director de Administración Ambiental, por la que se...
  Razonamiento: El texto corresponde a un "informe ambiental estratégico" de un Plan Especial, pero no es el acto administrativo princip

ID 45 | GT=['PROY_URB'] | PRED=['PLAN_ESP', 'PROY_URB']
  Falta: [] | Sobra: ['PLAN_ESP']
  Anuncio de aprobación provisional de cuenta de liquidación definitiva del proyecto de urba...
  Razonamiento: El texto menciona explícitamente un "Plan Parcial" (PLAN_ESP) y un "proyecto de urbanización" (PROY_URB). La aprobación

ID 51 | GT=['MOD_PUN'] | PRED=[]
  Falta: ['MOD_PUN'] | Sobra: []
  Informe Ambiental Estratégico de la Modificación Puntual 1/2022 de las Normas Subsidiarias...
  Razonamiento: El texto se refiere a una "Informe Ambiental Estratégico" de una modificación, no es un acto administrativo de aprobació

ID 59 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  ACUERDO de 26 de octubre de 2023, de la Comisión Territorial de Medio Ambiente y Urbanismo...
  Razonamiento: Texto: "modificación puntual n.º 3 de las Normas Urbanísticas Municipales" dispara MOD_PUN (regla 1). Mención explícita

ID 73 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PLAN_ESP']
  Falta: [] | Sobra: ['PLAN_ESP']
  Aprobación inicial de la modificación puntual n.º 8 del Plan Especial de Ordenación y Prot...
  Razonamiento: El texto menciona explícitamente "modificación puntual n.º 8" (disparador MOD_PUN) y también "Plan Especial de Ordenació

ID 75 | GT=['LIC_URB', 'PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: []
  INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rú...
  Razonamiento: Texto menciona explícitamente "autorización de uso excepcional de suelo rústico" en BOCYL (Castilla y León), lo que segú

ID 82 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PLAN_ESP']
  Falta: [] | Sobra: ['PLAN_ESP']
  ANUNCIO de la modificación puntual del Plan parcial de la unidad de ejecución número 1 del...
  Razonamiento: El texto menciona explícitamente "modificación puntual" (MOD_PUN) de un "Plan parcial" (PLAN_ESP). Al ser una modificaci

ID 83 | GT=['PROY_URB'] | PRED=['PGOU', 'PROY_URB']
  Falta: [] | Sobra: ['PGOU']
  ANUNCIO en relación a la información pública de la aprobación inicial del proyecto de repa...
  Razonamiento: El texto menciona "aprobación inicial del proyecto de reparcelación" y "unidad de ejecución", lo que indica una actuació

ID 90 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio por el que se somete a información pública la solicitud de autorización administra...
  Razonamiento: La publicación trata de una "planta solar fotovoltaica" con "autorización del proyecto", "licencia de obra mayor" y "eva

ID 91 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio por el que se somete a información pública la solicitud de autorización administra...
  Razonamiento: La publicación trata sobre una planta solar fotovoltaica, que es un proyecto de actividad energética y no urbanístico (t

ID 94 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio complementario del Departament d'Acció Climàtica, Alimentació i Agenda Rural - Ser...
  Razonamiento: El texto describe una solicitud de "autorización administrativa previa" y "declaración de utilidad pública" para un parq

ID 108 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rú...
  Razonamiento: nan

ID 126 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rú...
  Razonamiento: nan

ID 128 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio de los Servicios Territoriales del Departamento de Territorio, Vivienda y Transici...
  Razonamiento: La publicación trata sobre una "declaración de utilidad pública" (DUP) para un proyecto fotovoltaico solar, que es un tr

ID 130 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Resolución TER/58/2025, de 14 de enero, por la que se otorga a Els Plans Planta Fotovoltai...
  Razonamiento: Es una resolución que otorga la segunda "modificación de la autorización administrativa previa y de construcción y decla

ID 131 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio complementario por el que se somete a información pública la solicitud de autoriza...
  Razonamiento: La publicación trata sobre un proyecto solar fotovoltaico (parque Flix-Ascó III), lo cual cae en la categoría de planes

ID 132 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Resolución TER/4753/2024, de 17 de diciembre, por la que se otorga a Energía Inagotable de...
  Razonamiento: La publicación es una resolución de autorización administrativa para una planta solar fotovoltaica (proyecto energético)

ID 134 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Resolución TER/395/2025, de 10 de febrero, de corrección de errores materiales en la Resol...
  Razonamiento: El documento es una "Resolución de corrección de errores materiales" sobre un proyecto fotovoltaico, que corresponde a u

ID 140 | GT=['PGOU'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PLAN_ESP']
  Exposición pública Avance/Borrador del Plan General y el Plan de Ordenación Detallada de S...
  Razonamiento: El texto menciona "Plan General" (disparador PGOU) y "Plan de Ordenación Detallada" (equivalente a plan especial o estud

---

##  9. Experimento 4 - Prompt v4 (few-shot)

**Problema**: (rellenar tras el análisis de errores del §8)

**Objetivo**: Verificar si 5 ejemplos few-shot sobre los casos mas difíciles (MOD_PUN, PGOU variante regional, LIC_URB solar, falso positivo universidad, EMOT) eliminan los errores residuales.

**Enfoque**: Qwen 3.5 9B · SYSTEM_PROMPT_B2_V4 (V3 + 5 ejemplos) · few-shot · sin contexto N1.

**Resultados**: pendiente.

In [23]:
agent_b2_v4 = build_agent(
    model, "v4",
    output_type=ClassifierOutputB2,
    prompt_registry=PROMPT_REGISTRY_B2,
)

df_b2_exp4 = await run_experiment(
    agent_b2_v4, df_anotado_run,
    use_n1_context=False, concurrency=1,
    output_path="../results/b2_exp4_promptv4_qwen9b.csv",
    desc="B2 Exp4 - Prompt v4 few-shot",
)
df_b2_exp4.head(3)

  Reanudando: 149/150 registros ya clasificados

,id,bulletin,description,grupo_muestreo,is_relevant_gt,categories_gt,subcategories_gt,notas_anotador,is_relevant_pred,act_type_pred,categories_pred,subcategories_pred,confidence,reasoning,duration_s
0,0,boja,"Resolución de 16 de enero de 2025, de la Deleg...",PGOU,True,MOD_PUN,fase_definitiva,Publicacion registro Modificacion PGOU Mijas,True,resolución,"[""MOD_PUN"", ""PGOU""]","[""fase_definitiva""]",0.95,"La publicación es una resolución sobre la ""Mod...",62.526
1,1,bocm,Plan general de urbanismo\n– Acuerdo de 12 de ...,PGOU,True,MOD_PUN,fase_definitiva,Decimoctava Modificacion Puntual PGOU Getafe,True,acuerdo,"[""MOD_PUN""]","[""fase_definitiva"", ""uso_residencial""]",0.95,"El texto menciona ""modificación puntual"" (frag...",73.765
2,2,docm,"Anuncio de 28/01/2025, del Ayuntamiento de Vil...",PGOU,True,PLAN_ESP,fase_ip,PERIM exposicion publica - Plan Especial Refor...,True,anuncio,"[""PGOU""]","[""fase_ip""]",0.95,"El texto menciona ""Plan Especial de Reforma In...",64.691

In [24]:
df_b2_exp4 = pd.read_csv("../results/b2_exp4_promptv4_qwen9b.csv")
df_eval_b2_4 = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b2_exp4[["description","is_relevant_pred","act_type_pred","categories_pred",
                "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b2_4 = compute_metrics_B2(df_eval_b2_4, "Experimento B2-4 - Prompt v4 few-shot")
print_errors_B2(df_eval_b2_4, m_b2_4["exact"], m_b2_4["rel"], label="B2 Experimento 4 - Prompt v4 few-shot")

-- Experimento B2-4 - Prompt v4 few-shot --

is_relevant  Acc=0.934  P=1.000  R=0.927  F1=0.962
             TP=128  FP=0  FN=10  TN=14

N2 multilabel:
  Micro F1:      0.876
  Macro F1:      0.792
  Hamming Loss:  0.0373
  Jaccard:       0.763
  Subset Acc:    0.829

  Label             P      R     F1   Sup
  -------------------------------------
  PGOU          0.143  0.333  0.200     3
  PLAN_ESP      0.821  0.920  0.868    25
  MOD_PUN       0.976  0.909  0.941    44
  PROY_URB      1.000  0.739  0.850    23
  LIC_URB       0.944  0.850  0.895    40
  DIC_INT       1.000  1.000  1.000     5
  -------------------------------------
  Macro                       0.792

  Subset Acc por cardinalidad:
    card=0 (no relevante) : 1.000  (14/14)
    card=1 (1) : 0.824  (112/136)
    card=2 (2) : 0.000  (0/2)

  Confianza: media=0.950  min=0.750  max=1.000

-- Errores N2 en relevantes · B2 Experimento 4 - Prompt v4 few-shot --
Total: 26

ID 0 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  Resolución de 16 de enero de 2025, de la Delegación Territorial de Fomento, Articulación d...
  Razonamiento: La publicación es una resolución sobre la "Modificación del Plan General de Ordenación Urbana (PGOU) de Mijas". Aunque m

ID 2 | GT=['PLAN_ESP'] | PRED=['PGOU']
  Falta: ['PLAN_ESP'] | Sobra: ['PGOU']
  Anuncio de 28/01/2025, del Ayuntamiento de Villar de Olalla (Cuenca), sobre exposición púb...
  Razonamiento: El texto menciona "Plan Especial de Reforma Interior", que según las reglas N2 corresponde a la categoría PGOU al tratar

ID 3 | GT=['PROY_URB'] | PRED=['PGOU']
  Falta: ['PROY_URB'] | Sobra: ['PGOU']
  Anuncio de 27/12/2024, del Ayuntamiento de Albacete, de la Gerencia Municipal de Urbanismo...
  Razonamiento: "Anuncio... de la Gerencia Municipal de Urbanismo y Vivienda, sobre información pública del contenido de la plica presen

ID 4 | GT=['MOD_PUN'] | PRED=[]
  Falta: ['MOD_PUN'] | Sobra: []
  Viceconsejería de Planificación Territorial y Reto Demográfico.- Anuncio por el que se hac...
  Razonamiento: La publicación corresponde a un Informe Ambiental Estratégico en el marco de la Evaluación Ambiental, que es un procedim

ID 5 | GT=['PROY_URB'] | PRED=['PGOU']
  Falta: ['PROY_URB'] | Sobra: ['PGOU']
  Anuncio de 20 de febrero de 2025 sobre aprobación inicial del Programa de Ejecución de la ...
  Razonamiento: El texto menciona "Programa de Ejecución... de las Normas Subsidiarias", lo que en el ámbito autonómico (DOE) equivale a

ID 7 | GT=['MOD_PUN'] | PRED=[]
  Falta: ['MOD_PUN'] | Sobra: []
  EDICTO de aprobación del informe ambiental y territorial estratégico, por el procedimiento...
  Razonamiento: El texto hace referencia a una "modificación puntual" del plan general, pero el objeto es la "ordenación detallada", lo

ID 12 | GT=['PGOU'] | PRED=[]
  Falta: ['PGOU'] | Sobra: []
  RESOLUCIÓN de 28 de enero de 2025, del Instituto Aragonés de Gestión Ambiental, por la que...
  Razonamiento: La publicación es una "declaración ambiental estratégica" del plan, no el acto administrativo urbanístico (como aprobaci

ID 13 | GT=['PGOU'] | PRED=['MOD_PUN']
  Falta: ['PGOU'] | Sobra: ['MOD_PUN']
  Acuerdo de 25 de noviembre de 2024, del Ayuntamiento de Almedinilla, por el que se aprueba...
  Razonamiento: "Se aprueba definitivamente el documento de revisión parcial del Plan General", que corresponde a una modificación puntu

ID 15 | GT=['PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: ['LIC_URB']
  ACUERDO de 18 de febrero de 2025, del Pleno del Ayuntamiento de Saldaña de Burgos (Burgos)...
  Razonamiento: El texto menciona "acuerdo... aprueba definitivamente el proyecto de actuación de la unidad de actuación única", lo que

ID 20 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PGOU']
  Falta: [] | Sobra: ['PGOU']
  INFORMACIÓN pública relativa a la aprobación inicial de la modificación n.º 5 del Plan Gen...
  Razonamiento: Texto: "modificación n.º 5 del Plan General" indica modificación puntual (MOD_PUN) que menciona al PGOU como marco de re

ID 29 | GT=['PLAN_ESP'] | PRED=[]
  Falta: ['PLAN_ESP'] | Sobra: []
  Anuncio público a personas interesadas desconocidas en el procedimiento de evaluación ambi...
  Razonamiento: La descripción menciona "evaluación ambiental estratégica", que es un trámite administrativo distinto al urbanístico. Ad

ID 31 | GT=['PLAN_ESP', 'PROY_URB'] | PRED=['PLAN_ESP']
  Falta: ['PROY_URB'] | Sobra: []
  Aprobación inicial del Programa de Actuación, del cambio de sistema de gestión y de los es...
  Razonamiento: La descripción menciona explícitamente "Plan Parcial", que corresponde a la categoría PLAN_ESP (Regla 2). La fase es "in

ID 45 | GT=['PROY_URB'] | PRED=['PLAN_ESP']
  Falta: ['PROY_URB'] | Sobra: ['PLAN_ESP']
  Anuncio de aprobación provisional de cuenta de liquidación definitiva del proyecto de urba...
  Razonamiento: Texto: "Plan Parcial 'Cañada de la Morra Norte'" indica claramente que se trata de un Plan Especial (PLAN_ESP). Además,

ID 52 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PLAN_ESP']
  Falta: [] | Sobra: ['PLAN_ESP']
  Anuncio de 14/01/2025, del Ayuntamiento de Ciudad Real, sobre información pública de la Mo...
  Razonamiento: La descripción menciona tanto la "Modificación Puntual número 4 del Plan Parcial" (disparando PLAN_ESP, ya que es una ac

ID 64 | GT=['MOD_PUN'] | PRED=['LIC_URB', 'MOD_PUN']
  Falta: [] | Sobra: ['LIC_URB']
  ORDEN MAV/91/2025, de 4 de febrero, por la que se formula el informe ambiental estratégico...
  Razonamiento: "modificación puntual de las Normas Urbanísticas Municipales" indica el tipo de acto MOD_PUN, aunque menciona NNMM como

ID 73 | GT=['MOD_PUN'] | PRED=['MOD_PUN', 'PLAN_ESP']
  Falta: [] | Sobra: ['PLAN_ESP']
  Aprobación inicial de la modificación puntual n.º 8 del Plan Especial de Ordenación y Prot...
  Razonamiento: Texto indica "aprobación inicial" -> fase_inicial, y "modificación puntual n.º 8 del Plan Especial" -> MOD_PUN (priorita

ID 75 | GT=['LIC_URB', 'PROY_URB'] | PRED=['LIC_URB']
  Falta: ['PROY_URB'] | Sobra: []
  INFORMACIÓN pública relativa a la solicitud de autorización de uso excepcional de suelo rú...
  Razonamiento: Texto: "autorización de uso excepcional de suelo rústico" en BOCYL (Castilla y León) clasifica como LIC_URB (regla 4). F

ID 82 | GT=['MOD_PUN'] | PRED=['PLAN_ESP']
  Falta: ['MOD_PUN'] | Sobra: ['PLAN_ESP']
  ANUNCIO de la modificación puntual del Plan parcial de la unidad de ejecución número 1 del...
  Razonamiento: El texto menciona "modificación puntual del Plan parcial", lo que según las reglas implica la categoría PLAN_ESP, excluy

ID 90 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio por el que se somete a información pública la solicitud de autorización administra...
  Razonamiento: El texto describe un trámite administrativo energético (solicitud de autorización administrativa, proyecto solar fotovol

ID 92 | GT=['MOD_PUN'] | PRED=['PGOU']
  Falta: ['MOD_PUN'] | Sobra: ['PGOU']
  ORDEN MAV/239/2025, de 11 de marzo, por la que se aprueba definitivamente la modificación ...
  Razonamiento: El texto indica "se aprueba definitivamente la modificación del Plan General de Ordenación Urbana". Aunque menciona una

ID 94 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio complementario del Departament d'Acció Climàtica, Alimentació i Agenda Rural - Ser...
  Razonamiento: El texto describe una autorización administrativa previa para un parque solar (Flix-Ascó II), que es un trámite de energ

ID 129 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio complementario del Departamento de Territorio, Vivienda y Transición Ecológica de ...
  Razonamiento: La publicación pertenece al BOE (estatal) y trata sobre un proyecto de parque solar fotovoltaico, que es un trámite ener

ID 130 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Resolución TER/58/2025, de 14 de enero, por la que se otorga a Els Plans Planta Fotovoltai...
  Razonamiento: La publicación trata sobre una resolución administrativa relativa a una planta fotovoltaica, incluyendo "autorización pr

ID 131 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Anuncio complementario por el que se somete a información pública la solicitud de autoriza...
  Razonamiento: El texto se refiere a trámites de autorización administrativa para un parque solar, incluyendo "autorización del proyect

ID 132 | GT=['LIC_URB'] | PRED=[]
  Falta: ['LIC_URB'] | Sobra: []
  Resolución TER/4753/2024, de 17 de diciembre, por la que se otorga a Energía Inagotable de...
  Razonamiento: La publicación es una "Resolución" de otorgamiento de "autorización administrativa previa y de construcción" para una pl

ID 140 | GT=['PGOU'] | PRED=['PGOU', 'PLAN_ESP']
  Falta: [] | Sobra: ['PLAN_ESP']
  Exposición pública Avance/Borrador del Plan General y el Plan de Ordenación Detallada de S...
  Razonamiento: "Exposición pública Avance/Borrador del Plan General..." -> "Plan General" (PGOU) y "Plan de Ordenación Detallada" (PLAN

---

##  10. Comparativa de modelos - Gemma 4B con prompt V3

**Problema**: Todos los experimentos anteriores usan Qwen 3.5 9B. No sabemos si el prompt es transferible a modelos mas pequeños y rapidos.

**Objetivo**: Comprobar si Gemma 4 4B con V3 (no V4 por ventana de contexto) alcanza un rendimiento comparable al 9B.

**Enfoque**: Gemma 4 4B · SYSTEM_PROMPT_B2_V3 · zero-shot · sin contexto N1.

**Resultados**: pendiente.

In [ ]:
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider as OAIProvider

# Cargar gemma-4-e4b-it en LM Studio antes de ejecutar
model_gemma = OpenAIChatModel(
    "gemma-4-e4b-it",
    provider=OAIProvider(base_url="http://localhost:1234/v1", api_key="lm-studio")
)
agent_b2_gemma = build_agent(
    model_gemma, "v3",
    output_type=ClassifierOutputB2,
    prompt_registry=PROMPT_REGISTRY_B2,
)

df_b2_gemma = await run_experiment(
    agent_b2_gemma, df_anotado_run,
    use_n1_context=False, concurrency=1,
    output_path="../results/b2_exp_gemma4b.csv",
    desc="B2 Gemma4B - Prompt v3",
)
df_b2_gemma.head(3)

  Reanudando: 2/150 registros ya clasificados

B2 Gemma4B - Prompt v3:   1%|          | 1/148 [14:26<35:22:44, 866.43s/it]

  [SKIP] context overflow: 'Anuncio de 28/01/2025, del Ayuntamiento de Villar de Olalla (Cuenca), sobre expo'

B2 Gemma4B - Prompt v3:   1%|▏         | 2/148 [14:44<14:53:40, 367.27s/it]

  [SKIP] context overflow: 'Anuncio de 27/12/2024, del Ayuntamiento de Albacete, de la Gerencia Municipal de'

In [ ]:
df_b2_gemma = pd.read_csv("../results/b2_exp_gemma4b.csv")
df_eval_b2_gemma = df_anotado[["id","is_relevant_gt","categories_gt","subcategories_gt","description"]].merge(
    df_b2_gemma[["description","is_relevant_pred","act_type_pred","categories_pred",
                 "subcategories_pred","confidence","reasoning"]], on="description", how="left"
)
m_b2_gemma = compute_metrics_B2(df_eval_b2_gemma, "B2 Gemma 4B - Prompt v3")
print_errors_B2(df_eval_b2_gemma, m_b2_gemma["exact"], m_b2_gemma["rel"], label="B2 Gemma 4B - Prompt v3")

KeyError: "['is_relevant_pred', 'act_type_pred', 'categories_pred', 'subcategories_pred', 'confidence', 'reasoning'] not in index"

## 11. Tabla resumen - Comparativa de experimentos B2

In [ ]:
experimentos_cfg_B2 = [
    ("B2 Exp1 - Baseline V1",    "Qwen 3.5 9B", "Zero-shot", "../results/b2_exp1_baseline_qwen9b.csv"),
    ("B2 Exp2 - Prompt V2",      "Qwen 3.5 9B", "Zero-shot", "../results/b2_exp2_promptv2_qwen9b.csv"),
    ("B2 Exp3 - Prompt V3",      "Qwen 3.5 9B", "Zero-shot", "../results/b2_exp3_promptv3_qwen9b.csv"),
    ("B2 Exp4 - Prompt V4",      "Qwen 3.5 9B", "Few-shot",  "../results/b2_exp4_promptv4_qwen9b.csv"),
    ("B2 Exp5 - Gemma 4B V3",    "Gemma 4 4B",  "Zero-shot", "../results/b2_exp_gemma4b.csv"),
]

rows_b2 = []
metrics_list_b2 = []
for nombre, modelo, config, path in experimentos_cfg_B2:
    df_r = pd.read_csv(path)
    df_e = df_anotado[["id","is_relevant_gt","categories_gt","description"]].merge(
        df_r[["description","is_relevant_pred","categories_pred","confidence","duration_s"]],
        on="description", how="left"
    )
    m = compute_metrics_B2(df_e, verbose=False)
    metrics_list_b2.append({"Experimento": nombre, **m})
    rows_b2.append({
        "Experimento":     nombre,
        "Modelo":          modelo,
        "Config":          config,
        "is_rel_f1":       m["is_rel_f1"],
        "micro_f1":        m["micro_f1"],
        "macro_f1":        m["macro_f1"],
        "hamming_loss":    m["hamming_loss"],
        "jaccard_samples": m["jaccard_samples"],
        "subset_accuracy": m["subset_accuracy"],
        "mean_duration_s": round(df_r["duration_s"].mean(), 2) if "duration_s" in df_r.columns else None,
        "total_duration_s": round(df_r["duration_s"].sum(), 0) if "duration_s" in df_r.columns else None,
    })

df_summary_b2 = pd.DataFrame(rows_b2)
df_display_b2 = df_summary_b2.copy()
df_display_b2.columns = [
    "Experimento", "Modelo", "Config",
    "is_rel F1", "Micro F1", "Macro F1", "Hamming", "Jaccard", "Subset Acc",
    "s/item", "Total (s)",
]
display(df_display_b2.set_index("Experimento"))